package com.menora.initializr.extension.frontend.codegen;

import io.swagger.v3.oas.models.OpenAPI;
import org.springframework.stereotype.Component;

/**
 * Renders {@code errors.ts} — a tiny header file that exposes conditional types
 * for narrowing per-operation success/error response unions, plus a runtime
 * {@code isApiError} guard. Output is spec-shape-independent: every helper is
 * generic over {@code paths} so it works for any operation in the generated
 * {@code paths.ts}.
 *
 * <p>Kept as its own renderer (not inlined into {@link OpenApiTsGenerator}) so
 * callers that only want a subset of files can pick and choose.
 */
@Component
public class ErrorsTsRenderer {

    private static final String HEADER =
            "// AUTO-GENERATED by Menora Initializr from openapi.yaml — do not edit.\n"
                    + "// Re-generate with: pnpm gen:api\n\n";

    /**
     * Renders the file. {@code api} is currently unused (output is generic over
     * {@code paths}) but kept on the signature so future versions can inject
     * operation lists, custom error envelopes, etc. without changing callers.
     */
    public String render(OpenAPI api) {
        return HEADER
                + "import type { paths } from './paths'\n\n"
                + "type ResponsesOf<P extends keyof paths, M extends keyof paths[P]> =\n"
                + "  paths[P][M] extends { responses: infer R } ? R : never\n\n"
                + "/** Union of the 2xx body types declared on the operation. */\n"
                + "export type SuccessBody<P extends keyof paths, M extends keyof paths[P]> =\n"
                + "  ResponsesOf<P, M> extends { success: infer S }\n"
                + "    ? S[keyof S]\n"
                + "    : never\n\n"
                + "/** Union of the non-2xx body types (including `default`). */\n"
                + "export type ErrorBody<P extends keyof paths, M extends keyof paths[P]> =\n"
                + "  ResponsesOf<P, M> extends { error: infer E }\n"
                + "    ? E[keyof E]\n"
                + "    : never\n\n"
                + "/**\n"
                + " * Wraps a failed response. The client throws this from `requestJson()`\n"
                + " * so callers can `catch (e) { if (isApiError<'/pets','get'>(e)) ... }`.\n"
                + " */\n"
                + "export interface ApiError<P extends keyof paths, M extends keyof paths[P]> {\n"
                + "  status: number\n"
                + "  body: ErrorBody<P, M>\n"
                + "}\n\n"
                + "/**\n"
                + " * Runtime guard. Generics narrow the body type for the caller; at runtime\n"
                + " * we only check the shape (status: number, body: unknown).\n"
                + " */\n"
                + "export function isApiError<P extends keyof paths, M extends keyof paths[P]>(\n"
                + "  x: unknown,\n"
                + "): x is ApiError<P, M> {\n"
                + "  return typeof x === 'object' && x !== null\n"
                + "    && typeof (x as { status?: unknown }).status === 'number'\n"
                + "    && 'body' in (x as object)\n"
                + "}\n";
    }
}
