package com.menora.initializr.extension.frontend.codegen;

import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.Operation;
import io.swagger.v3.oas.models.PathItem;
import org.springframework.stereotype.Component;

import java.util.LinkedHashMap;
import java.util.Map;

/**
 * Renders {@code hooks.ts} — one React-Query binding per OpenAPI operation:
 *
 * <ul>
 *   <li>{@code GET} → {@code useXxx(params, opts)} wrapping {@link com.tanstack.react-query useQuery}</li>
 *   <li>{@code POST}/{@code PUT}/{@code PATCH}/{@code DELETE} →
 *       {@code useXxxMutation(opts)} wrapping {@code useMutation}</li>
 * </ul>
 *
 * <p>Gating is the caller's responsibility — this renderer assumes both
 * {@code api-client-openapi} and {@code data-tanstack-query} are selected.
 *
 * <p>operationId fallback: when an operation has no {@code operationId}, the
 * hook name is derived as {@code pascalCase(method + path)} so the file is
 * still self-describing.
 */
@Component
public class HooksTsRenderer {

    private static final String HEADER =
            "// AUTO-GENERATED by Menora Initializr from openapi.yaml — do not edit.\n"
                    + "// Re-generate with: pnpm gen:api\n\n";

    public String render(OpenAPI api) {
        StringBuilder sb = new StringBuilder(HEADER);
        sb.append("import {\n")
                .append("  useQuery,\n")
                .append("  useMutation,\n")
                .append("  type UseQueryOptions,\n")
                .append("  type UseMutationOptions,\n")
                .append("} from '@tanstack/react-query'\n");
        sb.append("import type { paths } from './paths'\n");
        sb.append("import type { ApiError, SuccessBody } from './errors'\n");
        sb.append("import { createApiClient } from './client'\n\n");
        sb.append("const api = createApiClient()\n\n");

        if (api.getPaths() == null || api.getPaths().isEmpty()) {
            sb.append("// (no paths in spec)\n");
            sb.append("export {}\n");
            return sb.toString();
        }

        for (Map.Entry<String, PathItem> e : api.getPaths().entrySet()) {
            String path = e.getKey();
            PathItem item = e.getValue();
            emitIfPresent(sb, path, "get", item.getGet());
            emitIfPresent(sb, path, "post", item.getPost());
            emitIfPresent(sb, path, "put", item.getPut());
            emitIfPresent(sb, path, "delete", item.getDelete());
            emitIfPresent(sb, path, "patch", item.getPatch());
        }
        return sb.toString();
    }

    private void emitIfPresent(StringBuilder sb, String path, String method, Operation op) {
        if (op == null) return;
        String hookName = hookName(method, path, op);
        String pathLiteral = "'" + path.replace("'", "\\'") + "'";
        String methodLiteral = "'" + method + "'";

        if ("get".equals(method)) {
            emitQueryHook(sb, hookName, pathLiteral, methodLiteral);
        } else {
            emitMutationHook(sb, hookName, pathLiteral, methodLiteral);
        }
    }

    private void emitQueryHook(StringBuilder sb, String hookName, String pathLiteral, String methodLiteral) {
        sb.append("export function use").append(hookName).append("<TData = SuccessBody<")
                .append(pathLiteral).append(", ").append(methodLiteral).append(">>(\n");
        sb.append("  init?: RequestInit,\n");
        sb.append("  opts?: Omit<\n");
        sb.append("    UseQueryOptions<SuccessBody<").append(pathLiteral).append(", ").append(methodLiteral)
                .append(">, ApiError<").append(pathLiteral).append(", ").append(methodLiteral)
                .append(">, TData>,\n");
        sb.append("    'queryKey' | 'queryFn'\n");
        sb.append("  >,\n");
        sb.append(") {\n");
        sb.append("  return useQuery({\n");
        sb.append("    queryKey: [").append(pathLiteral).append(", ").append(methodLiteral).append(", init],\n");
        sb.append("    queryFn: () => api.requestJson(").append(pathLiteral).append(", ").append(methodLiteral)
                .append(", init),\n");
        sb.append("    ...opts,\n");
        sb.append("  })\n");
        sb.append("}\n\n");
    }

    private void emitMutationHook(StringBuilder sb, String hookName, String pathLiteral, String methodLiteral) {
        sb.append("export function use").append(hookName).append("Mutation(\n");
        sb.append("  opts?: UseMutationOptions<\n");
        sb.append("    SuccessBody<").append(pathLiteral).append(", ").append(methodLiteral).append(">,\n");
        sb.append("    ApiError<").append(pathLiteral).append(", ").append(methodLiteral).append(">,\n");
        sb.append("    RequestInit | undefined\n");
        sb.append("  >,\n");
        sb.append(") {\n");
        sb.append("  return useMutation({\n");
        sb.append("    mutationFn: (init) => api.requestJson(").append(pathLiteral).append(", ").append(methodLiteral)
                .append(", init),\n");
        sb.append("    ...opts,\n");
        sb.append("  })\n");
        sb.append("}\n\n");
    }

    /**
     * operationId when present; otherwise {@code pascalCase(method + path)}.
     * Path templating ({@code /pets/{petId}}) becomes {@code PetsByPetId}.
     */
    static String hookName(String method, String path, Operation op) {
        if (op.getOperationId() != null && !op.getOperationId().isBlank()) {
            return pascalCase(op.getOperationId());
        }
        StringBuilder name = new StringBuilder();
        name.append(capitalize(method.toLowerCase()));
        for (String segment : path.split("/")) {
            if (segment.isEmpty()) continue;
            if (segment.startsWith("{") && segment.endsWith("}")) {
                String param = segment.substring(1, segment.length() - 1);
                if (param.isEmpty()) continue;
                name.append("By").append(capitalize(toIdentifier(param)));
            } else {
                name.append(capitalize(toIdentifier(segment)));
            }
        }
        return name.toString();
    }

    /** Splits on non-identifier chars (kebab, snake, dot) and PascalCases each piece. */
    private static String pascalCase(String input) {
        StringBuilder out = new StringBuilder();
        StringBuilder piece = new StringBuilder();
        for (int i = 0; i < input.length(); i++) {
            char c = input.charAt(i);
            if (Character.isJavaIdentifierPart(c)) {
                piece.append(c);
            } else if (piece.length() > 0) {
                out.append(capitalize(piece.toString()));
                piece.setLength(0);
            }
        }
        if (piece.length() > 0) out.append(capitalize(piece.toString()));
        return out.length() == 0 ? "Op" : out.toString();
    }

    private static String capitalize(String s) {
        if (s.isEmpty()) return s;
        return Character.toUpperCase(s.charAt(0)) + s.substring(1);
    }

    /** Strips characters TypeScript wouldn't accept in an identifier. */
    private static String toIdentifier(String segment) {
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < segment.length(); i++) {
            char c = segment.charAt(i);
            if (Character.isJavaIdentifierPart(c)) sb.append(c);
        }
        return sb.length() == 0 ? "X" : sb.toString();
    }

    /** Convenience for tests: produce a map keyed by file name. */
    Map<String, String> renderToMap(OpenAPI api) {
        Map<String, String> out = new LinkedHashMap<>();
        out.put("hooks.ts", render(api));
        return out;
    }
}
