package com.menora.initializr.extension.frontend.codegen;

import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.Operation;
import io.swagger.v3.oas.models.PathItem;
import io.swagger.v3.oas.models.media.MediaType;
import io.swagger.v3.oas.models.media.Schema;
import io.swagger.v3.oas.models.responses.ApiResponse;
import org.springframework.stereotype.Component;

import java.util.Map;

/**
 * Renders {@code msw.ts} — a set of <a href="https://mswjs.io">MSW v2</a>
 * handler stubs, one per OpenAPI operation, so generated projects have working
 * request mocks for Vitest / RTL out of the box.
 *
 * <p>Body resolution per operation (success response only):
 * <ol>
 *   <li>{@code response.content["application/json"].example}</li>
 *   <li>{@code response.content["application/json"].schema.example}</li>
 *   <li>Synthesised stub via {@link SchemaSampler}</li>
 * </ol>
 *
 * <p>Gating is the caller's responsibility — this assumes both
 * {@code api-client-openapi} and {@code test-vitest-rtl} are selected.
 */
@Component
public class MswHandlersRenderer {

    private static final String HEADER =
            "// AUTO-GENERATED by Menora Initializr from openapi.yaml — do not edit.\n"
                    + "// Re-generate with: pnpm gen:api\n\n";

    public String render(OpenAPI api) {
        StringBuilder sb = new StringBuilder(HEADER);
        sb.append("import { http, HttpResponse } from 'msw'\n\n");
        sb.append("export const handlers = [\n");
        if (api.getPaths() != null) {
            for (Map.Entry<String, PathItem> e : api.getPaths().entrySet()) {
                String path = e.getKey();
                PathItem item = e.getValue();
                emit(sb, api, path, "get", item.getGet());
                emit(sb, api, path, "post", item.getPost());
                emit(sb, api, path, "put", item.getPut());
                emit(sb, api, path, "delete", item.getDelete());
                emit(sb, api, path, "patch", item.getPatch());
            }
        }
        sb.append("]\n");
        return sb.toString();
    }

    private void emit(StringBuilder sb, OpenAPI api, String path, String method, Operation op) {
        if (op == null) return;
        SuccessPick pick = pickSuccess(op);
        String bodyJson = bodyFor(api, pick);
        String mswPath = toMswPath(path);
        int status = pick == null ? 200 : pick.statusCode();
        sb.append("  http.").append(method).append("('").append(mswPath.replace("'", "\\'")).append("', () => ")
                .append("HttpResponse.json(").append(bodyJson)
                .append(", { status: ").append(status).append(" })),\n");
    }

    @SuppressWarnings("rawtypes")
    private String bodyFor(OpenAPI api, SuccessPick pick) {
        if (pick == null) return "null";
        MediaType mt = pick.mediaType();
        if (mt == null) return "null";
        if (mt.getExample() != null) return toJsonLiteral(mt.getExample());
        Schema schema = mt.getSchema();
        if (schema == null) return "null";
        if (schema.getExample() != null) return toJsonLiteral(schema.getExample());
        return SchemaSampler.sampleJson(api, schema);
    }

    /** Picks the first 2xx response and its JSON content; falls back to default. */
    private SuccessPick pickSuccess(Operation op) {
        if (op.getResponses() == null) return null;
        // First 2xx wins; remember the default as a fallback.
        ApiResponse defaultResp = null;
        String defaultCode = null;
        for (Map.Entry<String, ApiResponse> r : op.getResponses().entrySet()) {
            String code = r.getKey();
            if ("default".equals(code)) {
                defaultResp = r.getValue();
                defaultCode = code;
                continue;
            }
            if (code != null && code.length() == 3 && code.charAt(0) == '2') {
                MediaType mt = pickJson(r.getValue());
                int status;
                try { status = Integer.parseInt(code); } catch (NumberFormatException ignore) { status = 200; }
                return new SuccessPick(status, mt);
            }
        }
        if (defaultResp != null) {
            return new SuccessPick(200, pickJson(defaultResp));
        }
        return new SuccessPick(200, null);
    }

    private MediaType pickJson(ApiResponse resp) {
        if (resp == null || resp.getContent() == null || resp.getContent().isEmpty()) return null;
        MediaType mt = resp.getContent().get("application/json");
        return mt != null ? mt : resp.getContent().values().iterator().next();
    }

    /** Turns {@code /pets/{petId}} into the MSW-compatible {@code /pets/:petId}. */
    static String toMswPath(String openApiPath) {
        StringBuilder sb = new StringBuilder();
        int i = 0;
        while (i < openApiPath.length()) {
            char c = openApiPath.charAt(i);
            if (c == '{') {
                int end = openApiPath.indexOf('}', i);
                if (end < 0) { sb.append(openApiPath.substring(i)); break; }
                sb.append(':').append(openApiPath, i + 1, end);
                i = end + 1;
            } else {
                sb.append(c);
                i++;
            }
        }
        return sb.toString();
    }

    /** Inline-serialise a value to a JSON literal acceptable in TS source. */
    private static String toJsonLiteral(Object value) {
        try {
            return new com.fasterxml.jackson.databind.ObjectMapper().writeValueAsString(value);
        } catch (Exception e) {
            return "null";
        }
    }

    private record SuccessPick(int statusCode, MediaType mediaType) {}
}
