package com.menora.initializr.extension.frontend.codegen;

import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.Operation;
import io.swagger.v3.oas.models.PathItem;
import io.swagger.v3.oas.models.media.MediaType;
import io.swagger.v3.oas.models.media.Schema;
import io.swagger.v3.oas.models.parameters.Parameter;
import io.swagger.v3.oas.models.parameters.RequestBody;
import io.swagger.v3.oas.models.responses.ApiResponse;
import io.swagger.v3.parser.OpenAPIV3Parser;
import io.swagger.v3.parser.core.models.SwaggerParseResult;
import org.springframework.stereotype.Component;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Generates TypeScript bindings ({@code schema.ts}, {@code paths.ts},
 * {@code client.ts}, {@code README.md}) from an OpenAPI 3 spec.
 *
 * <p>Goal: ship a usable typed client in the paired zip so the user doesn't
 * need to run {@code pnpm gen:api} before {@code tsc --noEmit} passes.
 * Coverage is the 80%: primitives, objects, arrays, refs, enums, nullable,
 * one/any/allOf. Edge cases degrade to {@code unknown} with a comment; the
 * shipped {@code gen:api} script (using {@code openapi-typescript}) remains
 * the regen escape hatch.
 *
 * <p>This generator is pure-Java — no Node, no subprocess. The whole pipeline
 * stays inside the JVM so the initializr container has no extra runtime deps.
 */
@Component
public class OpenApiTsGenerator {

    private static final String SCHEMA_HEADER =
            "// AUTO-GENERATED by Menora Initializr from openapi.yaml — do not edit.\n"
                    + "// Re-generate with: pnpm gen:api\n\n";

    private final ErrorsTsRenderer errorsRenderer;

    public OpenApiTsGenerator(ErrorsTsRenderer errorsRenderer) {
        this.errorsRenderer = errorsRenderer;
    }

    /**
     * Generates the typed client file set. Throws {@link OpenApiCodegenException}
     * if the spec cannot be parsed — caller decides whether to abort the whole
     * generation or just write a README pointing at {@code gen:api}.
     */
    public Map<String, String> generate(String specText) {
        return render(parse(specText));
    }

    /**
     * Parses a spec into a model without rendering. Exposed so callers that
     * also drive companion renderers (hooks, MSW) can share the parsed model
     * instead of re-parsing the same text.
     */
    public OpenAPI parse(String specText) {
        if (specText == null || specText.isBlank()) {
            throw new OpenApiCodegenException("Spec is empty");
        }
        SwaggerParseResult result = new OpenAPIV3Parser().readContents(specText);
        OpenAPI api = result.getOpenAPI();
        if (api == null) {
            String msg = (result.getMessages() == null || result.getMessages().isEmpty())
                    ? "Could not parse OpenAPI spec"
                    : String.join("; ", result.getMessages());
            throw new OpenApiCodegenException(msg);
        }
        return api;
    }

    /** Renders the core files from an already-parsed model. */
    public Map<String, String> render(OpenAPI api) {
        Map<String, String> out = new LinkedHashMap<>();
        out.put("schema.ts", renderSchemas(api));
        out.put("paths.ts", renderPaths(api));
        out.put("errors.ts", errorsRenderer.render(api));
        out.put("client.ts", renderClient());
        out.put("README.md", renderReadme(api));
        return out;
    }

    // ── schema.ts ───────────────────────────────────────────────────────────

    @SuppressWarnings({"rawtypes", "unchecked"})
    private String renderSchemas(OpenAPI api) {
        StringBuilder sb = new StringBuilder(SCHEMA_HEADER);
        Map<String, Schema> schemas = api.getComponents() == null
                ? Map.of()
                : (api.getComponents().getSchemas() == null ? Map.of() : api.getComponents().getSchemas());
        if (schemas.isEmpty()) {
            sb.append("// (no components.schemas in spec)\n");
            sb.append("export {}\n");
            return sb.toString();
        }
        for (Map.Entry<String, Schema> entry : schemas.entrySet()) {
            String name = entry.getKey();
            String body = TsTypeMapper.mapTopLevel(entry.getValue(), name);
            sb.append("export type ").append(name).append(" = ").append(body).append("\n\n");
        }
        return sb.toString();
    }

    // ── paths.ts ────────────────────────────────────────────────────────────

    private String renderPaths(OpenAPI api) {
        StringBuilder sb = new StringBuilder(SCHEMA_HEADER);
        sb.append("import type * as Schema from './schema'\n\n");
        sb.append("export type paths = {\n");
        if (api.getPaths() == null || api.getPaths().isEmpty()) {
            sb.append("  // (no paths in spec)\n");
            sb.append("}\n");
            return sb.toString();
        }
        for (Map.Entry<String, PathItem> entry : api.getPaths().entrySet()) {
            String path = entry.getKey();
            PathItem item = entry.getValue();
            sb.append("  '").append(escapeForKey(path)).append("': {\n");
            renderOperationIfPresent(sb, "get", item.getGet());
            renderOperationIfPresent(sb, "post", item.getPost());
            renderOperationIfPresent(sb, "put", item.getPut());
            renderOperationIfPresent(sb, "delete", item.getDelete());
            renderOperationIfPresent(sb, "patch", item.getPatch());
            renderOperationIfPresent(sb, "head", item.getHead());
            renderOperationIfPresent(sb, "options", item.getOptions());
            sb.append("  }\n");
        }
        sb.append("}\n");
        return sb.toString();
    }

    private void renderOperationIfPresent(StringBuilder sb, String method, Operation op) {
        if (op == null) return;
        renderOperationJsDoc(sb, op);
        sb.append("    ").append(method).append(": {\n");
        renderParameters(sb, op.getParameters());
        renderRequestBody(sb, op.getRequestBody());
        renderResponses(sb, op.getResponses());
        sb.append("    }\n");
    }

    /**
     * Emits a JSDoc block above an operation when the spec carries a summary,
     * description, or deprecated flag. Keeps the output cleaner when none of
     * those are set (the common case for hand-rolled internal specs).
     */
    private void renderOperationJsDoc(StringBuilder sb, Operation op) {
        String summary = op.getSummary();
        String description = op.getDescription();
        boolean deprecated = Boolean.TRUE.equals(op.getDeprecated());
        if ((summary == null || summary.isBlank())
                && (description == null || description.isBlank())
                && !deprecated) {
            return;
        }
        sb.append("    /**\n");
        if (summary != null && !summary.isBlank()) {
            for (String line : summary.split("\\r?\\n")) sb.append("     * ").append(line).append("\n");
        }
        if (description != null && !description.isBlank()) {
            if (summary != null && !summary.isBlank()) sb.append("     *\n");
            for (String line : description.split("\\r?\\n")) sb.append("     * ").append(line).append("\n");
        }
        if (deprecated) sb.append("     * @deprecated\n");
        sb.append("     */\n");
    }

    private void renderParameters(StringBuilder sb, List<Parameter> params) {
        if (params == null || params.isEmpty()) return;
        Map<String, List<Parameter>> byIn = new LinkedHashMap<>();
        for (Parameter p : params) {
            if (p == null || p.getName() == null) continue;
            byIn.computeIfAbsent(p.getIn() == null ? "query" : p.getIn(), k -> new java.util.ArrayList<>()).add(p);
        }
        if (byIn.isEmpty()) return;
        sb.append("      parameters: {\n");
        for (Map.Entry<String, List<Parameter>> grp : byIn.entrySet()) {
            boolean anyRequired = grp.getValue().stream().anyMatch(p -> Boolean.TRUE.equals(p.getRequired()));
            String key = grp.getKey();
            sb.append("        ").append(key).append(anyRequired ? "" : "?").append(": {\n");
            for (Parameter p : grp.getValue()) {
                String name = p.getName();
                String type = p.getSchema() == null ? "unknown" : TsTypeMapper.map(p.getSchema(), "Schema.");
                boolean req = Boolean.TRUE.equals(p.getRequired());
                sb.append("          '").append(name.replace("'", "\\'")).append("'").append(req ? "" : "?")
                        .append(": ").append(type).append("\n");
            }
            sb.append("        }\n");
        }
        sb.append("      }\n");
    }

    private void renderRequestBody(StringBuilder sb, RequestBody body) {
        if (body == null) return;
        String type = pickBodyType(body.getContent());
        if (type == null) return;
        boolean req = Boolean.TRUE.equals(body.getRequired());
        sb.append("      requestBody").append(req ? "" : "?").append(": ").append(type).append("\n");
    }

    /**
     * Splits responses into {@code success} (2xx) and {@code error} (everything
     * else — including {@code default}). The companion {@code errors.ts} relies
     * on this shape to infer the success-body and error-body unions per op.
     *
     * <p>Both buckets are always emitted (even when empty) so downstream
     * conditional types don't have to deal with missing keys.
     */
    private void renderResponses(StringBuilder sb, io.swagger.v3.oas.models.responses.ApiResponses responses) {
        Map<String, String> success = new LinkedHashMap<>();
        Map<String, String> error = new LinkedHashMap<>();
        if (responses != null) {
            for (Map.Entry<String, ApiResponse> r : responses.entrySet()) {
                String code = r.getKey();
                String type = pickBodyType(r.getValue().getContent());
                if (type == null) type = "unknown";
                if (isSuccessCode(code)) {
                    success.put(code, type);
                } else {
                    error.put(code, type);
                }
            }
        }
        sb.append("      responses: {\n");
        sb.append("        success: {");
        appendResponseBucket(sb, success);
        sb.append("}\n");
        sb.append("        error: {");
        appendResponseBucket(sb, error);
        sb.append("}\n");
        sb.append("      }\n");
    }

    private static boolean isSuccessCode(String code) {
        return code != null && code.length() == 3 && code.charAt(0) == '2';
    }

    private static void appendResponseBucket(StringBuilder sb, Map<String, String> bucket) {
        if (bucket.isEmpty()) return;
        sb.append("\n");
        for (Map.Entry<String, String> e : bucket.entrySet()) {
            sb.append("          '").append(e.getKey()).append("': ").append(e.getValue()).append("\n");
        }
        sb.append("        ");
    }

    /** Picks the schema for application/json or the first content entry that has one. */
    private String pickBodyType(io.swagger.v3.oas.models.media.Content content) {
        if (content == null || content.isEmpty()) return null;
        MediaType mt = content.get("application/json");
        if (mt == null) mt = content.values().iterator().next();
        if (mt == null || mt.getSchema() == null) return null;
        return TsTypeMapper.map(mt.getSchema(), "Schema.");
    }

    // ── client.ts ───────────────────────────────────────────────────────────

    private String renderClient() {
        return SCHEMA_HEADER
                + "import type { paths } from './paths'\n"
                + "import { type ApiError, type SuccessBody } from './errors'\n\n"
                + "type PathKey = keyof paths\n"
                + "type MethodOf<P extends PathKey> = keyof paths[P]\n\n"
                + "export interface ApiClientOptions {\n"
                + "  baseUrl?: string\n"
                + "  fetcher?: typeof fetch\n"
                + "}\n\n"
                + "/**\n"
                + " * Tiny typed-fetch wrapper. `path` and `method` are constrained to the\n"
                + " * paths/methods present in your OpenAPI spec, so a typo fails at compile time.\n"
                + " *\n"
                + " * - {@link request} returns the raw {@link Response} — use when you want\n"
                + " *   to inspect headers or stream the body.\n"
                + " * - {@link requestJson} parses JSON and narrows the body type for the\n"
                + " *   specific operation; throws an {@link ApiError} on non-2xx.\n"
                + " */\n"
                + "export function createApiClient(options: ApiClientOptions = {}) {\n"
                + "  // Vite injects VITE_API_BASE_URL when the project was generated with apiBaseUrl set.\n"
                + "  const envBase = (typeof import.meta !== 'undefined' && (import.meta as any).env?.VITE_API_BASE_URL) || ''\n"
                + "  const baseUrl = options.baseUrl ?? envBase\n"
                + "  const f = options.fetcher ?? fetch\n"
                + "  async function request<P extends PathKey, M extends MethodOf<P>>(\n"
                + "    path: P,\n"
                + "    method: M,\n"
                + "    init?: RequestInit,\n"
                + "  ): Promise<Response> {\n"
                + "    return f(baseUrl + (path as unknown as string), {\n"
                + "      ...init,\n"
                + "      method: (method as unknown as string).toUpperCase(),\n"
                + "    })\n"
                + "  }\n"
                + "  async function requestJson<P extends PathKey, M extends MethodOf<P>>(\n"
                + "    path: P,\n"
                + "    method: M,\n"
                + "    init?: RequestInit,\n"
                + "  ): Promise<SuccessBody<P, M>> {\n"
                + "    const res = await request(path, method, init)\n"
                + "    const body = await res.json().catch(() => undefined)\n"
                + "    if (!res.ok) {\n"
                + "      const err: ApiError<P, M> = { status: res.status, body: body as never }\n"
                + "      throw err\n"
                + "    }\n"
                + "    return body as SuccessBody<P, M>\n"
                + "  }\n"
                + "  return { request, requestJson }\n"
                + "}\n";
    }

    // ── README.md ───────────────────────────────────────────────────────────

    private String renderReadme(OpenAPI api) {
        String title = (api.getInfo() != null && api.getInfo().getTitle() != null) ? api.getInfo().getTitle() : "API";
        String version = (api.getInfo() != null && api.getInfo().getVersion() != null) ? api.getInfo().getVersion() : "?";
        return "# Generated API client\n\n"
                + "Pre-generated TypeScript bindings for **" + title + " v" + version + "**, produced by the\n"
                + "Menora Initializr paired generator at scaffolding time. You can use them immediately:\n\n"
                + "```ts\n"
                + "import { createApiClient } from './client'\n"
                + "const api = createApiClient()\n"
                + "const res = await api.request('/your/path', 'get')\n"
                + "```\n\n"
                + "## Regenerating\n\n"
                + "These files were produced by a pure-Java codegen that covers most common\n"
                + "shapes. For full coverage (especially exotic compositions), rerun the\n"
                + "battle-tested `openapi-typescript` CLI:\n\n"
                + "```bash\n"
                + "pnpm gen:api\n"
                + "```\n\n"
                + "That overwrites `schema.ts` with `openapi-typescript`'s output. The other\n"
                + "files (`paths.ts`, `client.ts`) stay — feel free to edit them.\n";
    }

    // ── Helpers ─────────────────────────────────────────────────────────────

    private static String escapeForKey(String path) {
        return path.replace("'", "\\'");
    }
}
