package com.menora.initializr.extension.frontend.codegen;

import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.Operation;
import io.swagger.v3.oas.models.PathItem;
import io.swagger.v3.oas.models.media.MediaType;
import io.swagger.v3.oas.models.media.Schema;
import io.swagger.v3.oas.models.parameters.Parameter;
import io.swagger.v3.oas.models.parameters.RequestBody;
import io.swagger.v3.oas.models.responses.ApiResponse;
import io.swagger.v3.parser.OpenAPIV3Parser;
import io.swagger.v3.parser.core.models.SwaggerParseResult;
import org.springframework.stereotype.Component;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Generates TypeScript bindings ({@code schema.ts}, {@code paths.ts},
 * {@code client.ts}, {@code README.md}) from an OpenAPI 3 spec.
 *
 * <p>Goal: ship a usable typed client in the paired zip so the user doesn't
 * need to run {@code pnpm gen:api} before {@code tsc --noEmit} passes.
 * Coverage is the 80%: primitives, objects, arrays, refs, enums, nullable,
 * one/any/allOf. Edge cases degrade to {@code unknown} with a comment; the
 * shipped {@code gen:api} script (using {@code openapi-typescript}) remains
 * the regen escape hatch.
 *
 * <p>This generator is pure-Java — no Node, no subprocess. The whole pipeline
 * stays inside the JVM so the initializr container has no extra runtime deps.
 */
@Component
public class OpenApiTsGenerator {

    private static final String SCHEMA_HEADER =
            "// AUTO-GENERATED by Menora Initializr from openapi.yaml — do not edit.\n"
                    + "// Re-generate with: pnpm gen:api\n\n";

    /**
     * Generates the typed client file set. Throws {@link OpenApiCodegenException}
     * if the spec cannot be parsed — caller decides whether to abort the whole
     * generation or just write a README pointing at {@code gen:api}.
     */
    public Map<String, String> generate(String specText) {
        if (specText == null || specText.isBlank()) {
            throw new OpenApiCodegenException("Spec is empty");
        }
        SwaggerParseResult result = new OpenAPIV3Parser().readContents(specText);
        OpenAPI api = result.getOpenAPI();
        if (api == null) {
            String msg = (result.getMessages() == null || result.getMessages().isEmpty())
                    ? "Could not parse OpenAPI spec"
                    : String.join("; ", result.getMessages());
            throw new OpenApiCodegenException(msg);
        }

        Map<String, String> out = new LinkedHashMap<>();
        out.put("schema.ts", renderSchemas(api));
        out.put("paths.ts", renderPaths(api));
        out.put("client.ts", renderClient());
        out.put("README.md", renderReadme(api));
        return out;
    }

    // ── schema.ts ───────────────────────────────────────────────────────────

    @SuppressWarnings({"rawtypes", "unchecked"})
    private String renderSchemas(OpenAPI api) {
        StringBuilder sb = new StringBuilder(SCHEMA_HEADER);
        Map<String, Schema> schemas = api.getComponents() == null
                ? Map.of()
                : (api.getComponents().getSchemas() == null ? Map.of() : api.getComponents().getSchemas());
        if (schemas.isEmpty()) {
            sb.append("// (no components.schemas in spec)\n");
            sb.append("export {}\n");
            return sb.toString();
        }
        for (Map.Entry<String, Schema> entry : schemas.entrySet()) {
            String name = entry.getKey();
            String body = TsTypeMapper.mapTopLevel(entry.getValue(), name);
            sb.append("export type ").append(name).append(" = ").append(body).append("\n\n");
        }
        return sb.toString();
    }

    // ── paths.ts ────────────────────────────────────────────────────────────

    private String renderPaths(OpenAPI api) {
        StringBuilder sb = new StringBuilder(SCHEMA_HEADER);
        sb.append("import type * as Schema from './schema'\n\n");
        sb.append("export type paths = {\n");
        if (api.getPaths() == null || api.getPaths().isEmpty()) {
            sb.append("  // (no paths in spec)\n");
            sb.append("}\n");
            return sb.toString();
        }
        for (Map.Entry<String, PathItem> entry : api.getPaths().entrySet()) {
            String path = entry.getKey();
            PathItem item = entry.getValue();
            sb.append("  '").append(escapeForKey(path)).append("': {\n");
            renderOperationIfPresent(sb, "get", item.getGet());
            renderOperationIfPresent(sb, "post", item.getPost());
            renderOperationIfPresent(sb, "put", item.getPut());
            renderOperationIfPresent(sb, "delete", item.getDelete());
            renderOperationIfPresent(sb, "patch", item.getPatch());
            renderOperationIfPresent(sb, "head", item.getHead());
            renderOperationIfPresent(sb, "options", item.getOptions());
            sb.append("  }\n");
        }
        sb.append("}\n");
        return sb.toString();
    }

    private void renderOperationIfPresent(StringBuilder sb, String method, Operation op) {
        if (op == null) return;
        sb.append("    ").append(method).append(": {\n");
        renderParameters(sb, op.getParameters());
        renderRequestBody(sb, op.getRequestBody());
        renderResponses(sb, op.getResponses());
        sb.append("    }\n");
    }

    private void renderParameters(StringBuilder sb, List<Parameter> params) {
        if (params == null || params.isEmpty()) return;
        Map<String, List<Parameter>> byIn = new LinkedHashMap<>();
        for (Parameter p : params) {
            if (p == null || p.getName() == null) continue;
            byIn.computeIfAbsent(p.getIn() == null ? "query" : p.getIn(), k -> new java.util.ArrayList<>()).add(p);
        }
        if (byIn.isEmpty()) return;
        sb.append("      parameters: {\n");
        for (Map.Entry<String, List<Parameter>> grp : byIn.entrySet()) {
            boolean anyRequired = grp.getValue().stream().anyMatch(p -> Boolean.TRUE.equals(p.getRequired()));
            String key = grp.getKey();
            sb.append("        ").append(key).append(anyRequired ? "" : "?").append(": {\n");
            for (Parameter p : grp.getValue()) {
                String name = p.getName();
                String type = p.getSchema() == null ? "unknown" : TsTypeMapper.map(p.getSchema(), "Schema.");
                boolean req = Boolean.TRUE.equals(p.getRequired());
                sb.append("          '").append(name.replace("'", "\\'")).append("'").append(req ? "" : "?")
                        .append(": ").append(type).append("\n");
            }
            sb.append("        }\n");
        }
        sb.append("      }\n");
    }

    private void renderRequestBody(StringBuilder sb, RequestBody body) {
        if (body == null) return;
        String type = pickBodyType(body.getContent());
        if (type == null) return;
        boolean req = Boolean.TRUE.equals(body.getRequired());
        sb.append("      requestBody").append(req ? "" : "?").append(": ").append(type).append("\n");
    }

    private void renderResponses(StringBuilder sb, io.swagger.v3.oas.models.responses.ApiResponses responses) {
        sb.append("      responses: {\n");
        if (responses != null) {
            for (Map.Entry<String, ApiResponse> r : responses.entrySet()) {
                String type = pickBodyType(r.getValue().getContent());
                if (type == null) type = "unknown";
                sb.append("        '").append(r.getKey()).append("': ").append(type).append("\n");
            }
        }
        sb.append("      }\n");
    }

    /** Picks the schema for application/json or the first content entry that has one. */
    private String pickBodyType(io.swagger.v3.oas.models.media.Content content) {
        if (content == null || content.isEmpty()) return null;
        MediaType mt = content.get("application/json");
        if (mt == null) mt = content.values().iterator().next();
        if (mt == null || mt.getSchema() == null) return null;
        return TsTypeMapper.map(mt.getSchema(), "Schema.");
    }

    // ── client.ts ───────────────────────────────────────────────────────────

    private String renderClient() {
        return SCHEMA_HEADER
                + "import type { paths } from './paths'\n\n"
                + "type PathKey = keyof paths\n"
                + "type MethodOf<P extends PathKey> = keyof paths[P]\n\n"
                + "export interface ApiClientOptions {\n"
                + "  baseUrl?: string\n"
                + "  fetcher?: typeof fetch\n"
                + "}\n\n"
                + "/**\n"
                + " * Tiny typed-fetch wrapper. `path` and `method` are constrained to the\n"
                + " * paths/methods present in your OpenAPI spec, so a typo fails at compile time.\n"
                + " * Response payloads are still typed as `Response` — use `await res.json()`\n"
                + " * and cast to `paths[P][M]['responses']['200']` when you need the typed body.\n"
                + " */\n"
                + "export function createApiClient(options: ApiClientOptions = {}) {\n"
                + "  // Vite injects VITE_API_BASE_URL when the project was generated with apiBaseUrl set.\n"
                + "  const envBase = (typeof import.meta !== 'undefined' && (import.meta as any).env?.VITE_API_BASE_URL) || ''\n"
                + "  const baseUrl = options.baseUrl ?? envBase\n"
                + "  const f = options.fetcher ?? fetch\n"
                + "  return {\n"
                + "    async request<P extends PathKey, M extends MethodOf<P>>(\n"
                + "      path: P,\n"
                + "      method: M,\n"
                + "      init?: RequestInit,\n"
                + "    ): Promise<Response> {\n"
                + "      return f(baseUrl + (path as unknown as string), {\n"
                + "        ...init,\n"
                + "        method: (method as unknown as string).toUpperCase(),\n"
                + "      })\n"
                + "    },\n"
                + "  }\n"
                + "}\n";
    }

    // ── README.md ───────────────────────────────────────────────────────────

    private String renderReadme(OpenAPI api) {
        String title = (api.getInfo() != null && api.getInfo().getTitle() != null) ? api.getInfo().getTitle() : "API";
        String version = (api.getInfo() != null && api.getInfo().getVersion() != null) ? api.getInfo().getVersion() : "?";
        return "# Generated API client\n\n"
                + "Pre-generated TypeScript bindings for **" + title + " v" + version + "**, produced by the\n"
                + "Menora Initializr paired generator at scaffolding time. You can use them immediately:\n\n"
                + "```ts\n"
                + "import { createApiClient } from './client'\n"
                + "const api = createApiClient()\n"
                + "const res = await api.request('/your/path', 'get')\n"
                + "```\n\n"
                + "## Regenerating\n\n"
                + "These files were produced by a pure-Java codegen that covers most common\n"
                + "shapes. For full coverage (especially exotic compositions), rerun the\n"
                + "battle-tested `openapi-typescript` CLI:\n\n"
                + "```bash\n"
                + "pnpm gen:api\n"
                + "```\n\n"
                + "That overwrites `schema.ts` with `openapi-typescript`'s output. The other\n"
                + "files (`paths.ts`, `client.ts`) stay — feel free to edit them.\n";
    }

    // ── Helpers ─────────────────────────────────────────────────────────────

    private static String escapeForKey(String path) {
        return path.replace("'", "\\'");
    }
}
