server:
  port: 8080

admin:
  password: changeme

spring:
  cache:
    type: jcache
  datasource:
    url: jdbc:h2:file:./data/initializr
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  h2:
    console:
      enabled: true
      path: /h2-console

initializr:
  group-id:
    value: com.menora
  artifact-id:
    value: demo
  version:
    value: 0.0.1-SNAPSHOT
  name:
    value: demo
  description:
    value: Menora Spring Boot project
  package-name:
    value: com.menora.demo
  java-versions:
    - id: 21
      default: true
    - id: 17
  languages:
    - name: Java
      id: java
      default: true
    - name: Kotlin
      id: kotlin
  boot-versions:
    - id: 3.2.1
      name: 3.2.1
      default: true
  configuration-file-formats:
    - name: properties
      id: properties
      default: true
    - name: yaml
      id: yaml
  packagings:
    - name: Jar
      id: jar
      default: true
    - name: War
      id: war
  types:
    - name: Maven Project
      id: maven-project
      description: Generate a Maven-based project archive
      default: true
      action: /starter.zip
      tags:
        build: maven
        format: project
    - name: Gradle Project
      id: gradle-project
      description: Generate a Gradle-based project archive
      action: /starter.zip
      tags:
        build: gradle
        format: project
  env:
    repositories:
      menora-release:
        name: Menora Artifactory Releases
        url: https://repo.menora.co.il/artifactory/libs-release
        releases-enabled: true
        snapshots-enabled: false
      menora-snapshot:
        name: Menora Artifactory Snapshots
        url: https://repo.menora.co.il/artifactory/libs-snapshot
        releases-enabled: false
        snapshots-enabled: true
management:
  endpoints:
    web:
      exposure:
        include: health,info
