spring:
  mail:
    host: ${MAIL_HOST:smtp.office365.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    default-encoding: UTF-8

mail:
  imap:
    host: ${MAIL_IMAP_HOST:outlook.office365.com}
    port: ${MAIL_IMAP_PORT:993}
    folder: ${MAIL_IMAP_FOLDER:INBOX}
