package com.menora.initializr;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.web.client.TestRestTemplate;
import org.springframework.context.annotation.Import;
import org.springframework.core.io.ClassPathResource;
import org.springframework.http.HttpEntity;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpMethod;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.TreeMap;
import java.util.function.Consumer;
import java.util.zip.ZipEntry;
import java.util.zip.ZipInputStream;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * The fullstack frontend page layout ({@code pages}): dashboards, entity-list pages with preset
 * filters, and tabs pages rendered as {@code src/app/screens/*}, plus the classic layout when the
 * request has no pages. Generated bytes are pinned with {@code contains}; the real type-check/lint
 * runs in {@code GeneratedFrontendBuildSmokeTests.fullstackFrontendPageLayouts*}.
 */
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
@Import(TestInvokerConfiguration.class)
class FullstackPagesIntegrationTests {

    private static final String FE = "support/frontend/";

    @Autowired
    private TestRestTemplate restTemplate;

    @Test
    void fullstackEndpoint_rendersPageTypes() throws Exception {
        Map<String, String> files = generate(exampleBody("tickets", "react-tailwind-crud"));

        // Shell: nav over the visible pages only, in declaration order, opening on the first.
        String app = files.get(FE + "src/app/App.tsx");
        assertThat(app)
                .contains("import { Layers, LayoutDashboard, Menu, Moon, Sun, Table2 } from 'lucide-react'")
                .contains("import { OverviewScreen } from '@app/screens/OverviewScreen'")
                .contains("import { QueueScreen } from '@app/screens/QueueScreen'")
                .contains("type View = 'overview' | 'queue' | 'agents' | 'teams'")
                .contains("{ id: 'overview', label: 'Support overview', icon: LayoutDashboard },")
                .contains("{ id: 'queue', label: 'Ticket queue', icon: Layers },")
                .contains("{ id: 'agents', label: 'Agents', icon: Table2 },")
                .contains("useState<View>('overview')")
                .contains("{view === 'overview' && <OverviewScreen onNavigate={v => go(v as View)} />}")
                .contains("{view === 'agents' && <AgentsScreen />}")
                .doesNotContain("DashboardPage")
                .doesNotContain("TicketsOpenScreen");

        // Dashboard: widgets in order; only the Agent/Team KPIs link (Ticket has no visible list page).
        String overview = files.get(FE + "src/app/screens/OverviewScreen.tsx");
        assertThat(overview)
                .contains("import { BreakdownCard, KpiTile, RecentList, } from '@shared/ui/widgets'")
                .contains("import { t } from '@shared/i18n'")
                .contains("import { TicketStatusTypeLabels, TicketPriorityTypeLabels } from '@entities/ticket'")
                .contains("export function OverviewScreen({ onNavigate }: Props)")
                .contains("text-fg\">{ 'Support overview' }</h1>")
                .contains("title={ 'Agents' }\n          path=\"/api/agents\"\n          onOpen={() => onNavigate('agents')}")
                .contains("field=\"status\"\n            labels={ TicketStatusTypeLabels }")
                .contains("title={ t('xByY', { x: 'Tickets', y: 'Priority' }) }")
                .contains("title={ t('recentX', { x: 'Tickets' }) }")
                .contains("sortField=\"id\"\n            displayField=\"subject\"\n            limit={ 5 }");
        assertThat(files.get(FE + "src/shared/ui/widgets.tsx"))
                .contains("export function KpiTile(")
                .contains("export function BreakdownCard(")
                .contains("export function RecentList(");

        // Tabs embed hidden list pages; those pass preset filters into the entity page.
        String queue = files.get(FE + "src/app/screens/QueueScreen.tsx");
        assertThat(queue)
                .contains("import { TicketsOpenScreen } from './TicketsOpenScreen'")
                .contains("{ id: 'tickets-in-progress', label: 'In progress' },")
                .contains("aria-label={ 'Ticket queue' }")
                .contains("{active === 2 && (")
                .contains("<TicketsAllScreen />")
                .doesNotContain("onNavigate")
                .doesNotContain("@shared/i18n");
        assertThat(files.get(FE + "src/app/screens/TicketsOpenScreen.tsx"))
                .isEqualTo("import { TicketPage } from '@pages/ticket'\n\n"
                        + "export function TicketsOpenScreen() {\n"
                        + "  return <TicketPage initialFilters={ { status: 'OPEN' } } />\n"
                        + "}\n");
        assertThat(files.get(FE + "src/app/screens/TicketsAllScreen.tsx"))
                .contains("return <TicketPage />");
        assertThat(files.get(FE + "src/pages/ticket/ui/TicketPage.tsx"))
                .contains("export function TicketPage({ initialFilters }: { initialFilters?: FilterValues } = {}) {")
                .contains("useState<FilterValues>(initialFilters ?? {})");
        // An entity without filters keeps the zero-arg page.
        assertThat(files.get(FE + "src/pages/team/ui/TeamPage.tsx")).contains("export function TeamPage() {");

        // Chrome strings the widgets read ship in both tables.
        assertThat(files.get(FE + "src/shared/i18n/strings.ts"))
                .contains("recentX: 'Recent {x}'")
                .contains("viewAll: 'הצג הכל'");
    }

    @Test
    void fullstackEndpoint_withoutPagesKeepsTheClassicShell() throws Exception {
        Map<String, Object> body = exampleBody("tickets", "react-tailwind-crud");
        body.remove("pages");
        Map<String, String> files = generate(body);

        assertThat(files.get(FE + "src/app/App.tsx"))
                .contains("import { LayoutDashboard, Menu, Moon, Sun, Table2 } from 'lucide-react'")
                .contains("import { DashboardPage } from '@pages/dashboard'")
                .contains("type View = 'dashboard' | 'team' | 'agent' | 'ticket'")
                .contains("useState<View>('dashboard')")
                .doesNotContain("Screen");
        assertThat(files.keySet()).noneMatch(p -> p.contains("/screens/") || p.endsWith("widgets.tsx"));
        assertThat(files.get(FE + "src/pages/ticket/ui/TicketPage.tsx"))
                .contains("export function TicketPage() {")
                .contains("useState<FilterValues>({})");
    }

    @Test
    void fullstackEndpoint_menoraSetSkinsTabsPagesAndBorrowsTheRest() throws Exception {
        Map<String, String> files = generate(exampleBody("orders", "react-menora-digital-crud"));
        String fe = "support/frontend/";

        assertThat(files.get(fe + "src/app/App.tsx"))
                .contains("import { CatalogScreen } from '@app/screens/CatalogScreen'")
                .contains("{ id: 'desk', label: 'Sales desk' },")
                .contains("<NavLinks")
                .doesNotContain("DashboardPage");
        assertThat(files.get(fe + "src/app/screens/CatalogScreen.tsx"))
                .contains("import { Tabs } from '@shared/ui/menora'")
                .contains("{ id: 'products', label: 'Products', panelId: 'products-panel' },")
                .contains("<Tabs items={TABS} activeIndex={active} onChange={setActive} ariaLabel={ 'Catalog' } bare />");
        assertThat(files.get(fe + "src/app/screens/DeskScreen.tsx"))
                .contains("<p className=\"mt-1 max-w-2xl text-sm text-muted\">{ 'Orders at a glance: volume, status mix and the latest orders.' }</p>")
                // Order has a visible list page, so its KPI links; Customer's list is only in a tab.
                .contains("path=\"/api/orders\"\n          onOpen={() => onNavigate('orders')}")
                .contains("title={ 'Customers' }\n          path=\"/api/customers\"\n        />");
        assertThat(files.get(fe + "src/shared/ui/widgets.tsx")).contains("export function KpiTile(");
    }

    @Test
    void fullstackEndpoint_escapesUserTextInPageLabels() throws Exception {
        Map<String, Object> body = exampleBody("tickets", "react-tailwind-crud");
        List<Map<String, Object>> pages = pages(body);
        pages.get(0).put("title", "Agent's \"desk\"\nnow");
        Map<String, String> files = generate(body);

        assertThat(files.get(FE + "src/app/App.tsx"))
                .contains("{ id: 'overview', label: 'Agent\\'s \"desk\"\\nnow', icon: LayoutDashboard },");
    }

    @Test
    void fullstackEndpoint_rejectsInvalidPages() {
        assertRejected(p -> p.get(0).put("type", "master-detail"), "type 'master-detail' is not supported yet");
        assertRejected(p -> p.get(0).put("type", "gallery"), "unknown type 'gallery'");
        assertRejected(p -> p.get(0).put("id", "Overview"), "Page id 'Overview' must be lower-case");
        assertRejected(p -> p.get(5).put("id", "overview"), "Duplicate page id 'overview'");
        assertRejected(p -> p.get(5).put("entity", "Customer"), "unknown entity 'Customer'");
        assertRejected(p -> p.get(0).put("entity", "Ticket"), "(dashboard) does not take 'entity'");
        assertRejected(p -> p.get(0).put("widgets", List.of()), "needs at least one widget");
        assertRejected(p -> p.get(0).put("widgets", List.of(Map.of("kind", "bar", "entity", "Ticket", "groupBy", "subject"))),
                "groupBy 'subject' must be a non-key enum or boolean field");
        assertRejected(p -> p.get(0).put("widgets", List.of(Map.of("kind", "bar", "entity", "Team"))),
                "Team has no enum or boolean field to group by");
        assertRejected(p -> p.get(0).put("widgets", List.of(Map.of("kind", "kpi", "entity", "Ticket", "agg", "sum"))),
                "agg 'sum' is not supported yet");
        assertRejected(p -> p.get(0).put("widgets", List.of(Map.of("kind", "recent", "entity", "Ticket", "limit", 99))),
                "limit must be between 1 and 20");
        assertRejected(p -> p.get(1).put("tabs", List.of(Map.of("page", "tickets-open"))), "needs between 2 and 6 tabs");
        assertRejected(p -> p.get(1).put("tabs", List.of(Map.of("page", "tickets-open"), Map.of("page", "queue"))),
                "a tab cannot embed another tabs page ('queue')");
        assertRejected(p -> p.get(1).put("tabs", List.of(Map.of("page", "tickets-open"), Map.of("page", "nope"))),
                "no page with id 'nope'");
        assertRejected(p -> p.get(1).remove("title"), "Page 'queue' (tabs) needs a title");
        assertRejected(p -> p.get(2).put("presetFilter", Map.of("status", "LOST")), "'LOST' is not one of");
        assertRejected(p -> p.get(2).put("presetFilter", Map.of("subject", "x")),
                "only filterable enum or boolean fields can be preset");
        assertRejected(p -> p.forEach(page -> page.put("hidden", true)), "At least one page must be visible");
    }

    @Test
    void fullstackEndpoint_canonicalizesPresetFilterAndEntityNames() throws Exception {
        Map<String, Object> body = exampleBody("tickets", "react-tailwind-crud");
        List<Map<String, Object>> pages = pages(body);
        pages.get(2).put("entity", "ticket");
        pages.get(2).put("presetFilter", Map.of("status", "open"));
        Map<String, String> files = generate(body);

        assertThat(files.get(FE + "src/app/screens/TicketsOpenScreen.tsx"))
                .contains("<TicketPage initialFilters={ { status: 'OPEN' } } />");
    }

    // ── Helpers ─────────────────────────────────────────────────────────────

    private void assertRejected(Consumer<List<Map<String, Object>>> mutator, String expectedMessage) {
        Map<String, Object> body = exampleBody("tickets", "react-tailwind-crud");
        mutator.accept(pages(body));
        ResponseEntity<String> response = restTemplate.exchange("/starter-fullstack.zip", HttpMethod.POST,
                new HttpEntity<>(body, jsonHeaders()), String.class);
        assertThat(response.getStatusCode()).as(expectedMessage).isEqualTo(HttpStatus.BAD_REQUEST);
        assertThat(response.getBody()).contains(expectedMessage);
    }

    @SuppressWarnings("unchecked")
    private static List<Map<String, Object>> pages(Map<String, Object> body) {
        return (List<Map<String, Object>>) body.get("pages");
    }

    /** A fullstack request built from a seeded example's entities + pages (mutable copies). */
    static Map<String, Object> exampleBody(String exampleId, String frontendSet) {
        try (InputStream in = new ClassPathResource("catalog/fullstack-examples.json").getInputStream()) {
            List<Map<String, Object>> examples = new ObjectMapper().readValue(in, new TypeReference<>() {});
            Map<String, Object> example = examples.stream()
                    .filter(e -> exampleId.equals(e.get("exampleId"))).findFirst().orElseThrow();
            Map<String, Object> body = new LinkedHashMap<>();
            body.put("artifactId", "support");
            body.put("packageName", "com.menora.support");
            body.put("bootVersion", "3.2.1");
            body.put("frontendTemplateSet", frontendSet);
            body.put("entities", example.get("entities"));
            body.put("pages", new ArrayList<>(example.get("pages") == null ? List.of()
                    : ((List<Map<String, Object>>) example.get("pages")).stream()
                            .map(p -> (Map<String, Object>) new LinkedHashMap<>(p)).toList()));
            return body;
        } catch (java.io.IOException e) {
            throw new IllegalStateException(e);
        }
    }

    private Map<String, String> generate(Map<String, Object> body) throws Exception {
        ResponseEntity<byte[]> response = restTemplate.exchange("/starter-fullstack.zip", HttpMethod.POST,
                new HttpEntity<>(body, jsonHeaders()), byte[].class);
        assertThat(response.getStatusCode())
                .as(response.getBody() == null ? "" : new String(response.getBody(), StandardCharsets.UTF_8))
                .isEqualTo(HttpStatus.OK);
        Map<String, String> result = new TreeMap<>();
        try (ZipInputStream zin = new ZipInputStream(new ByteArrayInputStream(response.getBody()))) {
            ZipEntry entry;
            while ((entry = zin.getNextEntry()) != null) {
                if (entry.isDirectory()) continue;
                ByteArrayOutputStream out = new ByteArrayOutputStream();
                zin.transferTo(out);
                result.put(entry.getName(), out.toString(StandardCharsets.UTF_8));
            }
        }
        return result;
    }

    private static HttpHeaders jsonHeaders() {
        HttpHeaders headers = new HttpHeaders();
        headers.setContentType(MediaType.APPLICATION_JSON);
        return headers;
    }
}
