package com.menora.initializr;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.web.client.TestRestTemplate;
import org.springframework.context.annotation.Import;
import org.springframework.core.io.ClassPathResource;
import org.springframework.http.HttpEntity;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpMethod;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.TreeMap;
import java.util.function.Consumer;
import java.util.zip.ZipEntry;
import java.util.zip.ZipInputStream;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * The fullstack frontend page layout ({@code pages}): dashboards, entity-list pages with preset
 * filters, tabs, master-detail and record pages rendered as {@code src/app/screens/*}, plus the
 * classic layout when the request has no pages. Generated bytes are pinned with {@code contains}; the real type-check/lint
 * runs in {@code GeneratedFrontendBuildSmokeTests.fullstackFrontendPageLayouts*}.
 */
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
@Import(TestInvokerConfiguration.class)
class FullstackPagesIntegrationTests {

    private static final String FE = "support/frontend/";

    @Autowired
    private TestRestTemplate restTemplate;

    @Test
    void fullstackEndpoint_rendersPageTypes() throws Exception {
        Map<String, String> files = generate(exampleBody("tickets", "react-tailwind-crud"));

        // Shell: nav over the visible pages only, grouped into the example's sections (a section
        // gathers its pages where the group first appears), with their icons.
        String app = files.get(FE + "src/app/App.tsx");
        assertThat(app)
                .contains("import { Inbox, LayoutDashboard, Menu, Moon, PanelLeft, Sun, Users } from 'lucide-react'")
                .contains("import { useRoute, type View } from '@app/route'")
                .contains("import { OverviewScreen } from '@app/screens/OverviewScreen'")
                .contains("import { QueueScreen } from '@app/screens/QueueScreen'")
                .contains("  {\n    label: '',\n    items: [\n      { id: 'overview', label: 'Support overview', icon: LayoutDashboard },\n    ],\n  },")
                .contains("  {\n    label: 'Work',\n    items: [\n      { id: 'queue', label: 'Ticket queue', icon: Inbox },\n    ],\n  },")
                .contains("    label: 'People',\n    items: [\n      { id: 'agents', label: 'Agents', icon: Users },\n"
                        + "      { id: 'teams', label: 'Teams', icon: PanelLeft },\n    ],")
                .contains("const [route, navigate] = useRoute()")
                .contains("{view === 'overview' && <OverviewScreen onNavigate={goView} />}")
                // The route hands a tabs page its open tab, and a filterable list its filters.
                .contains("{view === 'queue' && <QueueScreen tab={route.arg} onTabChange={tab => go('queue', tab)} />}")
                .contains("{view === 'agents' && <AgentsScreen filters={route.query} />}")
                .contains("{view === 'teams' && <TeamsScreen />}")
                .doesNotContain("DashboardPage")
                .doesNotContain("TicketsOpenScreen")
                .doesNotContain("RECORD_TITLES");
        // The route: every page the shell shows, parsed from the hash, falling back to the start page.
        assertThat(files.get(FE + "src/app/route.ts"))
                .contains("export type View = 'overview' | 'queue' | 'agents' | 'teams'")
                .contains("const VIEWS: readonly View[] = ['overview', 'queue', 'agents', 'teams']")
                .contains("if (!view) return { view: 'overview', query: {} }")
                .contains("window.addEventListener('hashchange', onHashChange)")
                // No record pages: nothing needs an id to open.
                .doesNotContain("RECORD_VIEWS");
        assertThat(files.get(FE + "src/app/screens/QueueScreen.tsx"))
                .contains("export function QueueScreen({ tab: openTab, onTabChange }: Props) {")
                .contains("const active = Math.max(0, TABS.findIndex(x => x.id === openTab))")
                .doesNotContain("useState");
        // A preset list merges the route's filters over its own.
        assertThat(files.get(FE + "src/app/screens/TicketsOpenScreen.tsx"))
                .contains("key={JSON.stringify(filters ?? {})}")
                .contains("initialFilters={ { status: 'OPEN', ...filters } }");
        assertThat(files.get(FE + "src/app/screens/AgentsScreen.tsx")).contains("initialFilters={filters}");

        // Dashboard: widgets in order. Ticket's list pages are only tabs, so its widgets open the
        // tabs page; Team's home is its master-detail page.
        String overview = files.get(FE + "src/app/screens/OverviewScreen.tsx");
        assertThat(overview)
                .contains("import { BreakdownCard, KpiTile, RecentList, } from '@shared/ui/widgets'")
                .contains("import { t } from '@shared/i18n'")
                .contains("import { TicketStatusTypeLabels, TicketPriorityTypeLabels } from '@entities/ticket'")
                .contains("export function OverviewScreen({ onNavigate }: Props)")
                .contains("text-fg\">{ 'Support overview' }</h1>")
                .contains("title={ 'Agents' }\n          path=\"/api/agents\"\n          onOpen={() => onNavigate('agents')}")
                .contains("title={ 'Tickets' }\n          path=\"/api/tickets\"\n          onOpen={() => onNavigate('queue')}")
                .contains("title={ 'Teams' }\n          path=\"/api/teams\"\n          onOpen={() => onNavigate('teams')}")
                .contains("export function OverviewScreen({ onNavigate }: Props)")
                .contains("onNavigate: (view: string, arg?: string, query?: Record<string, string>) => void")
                // Charts and lists take two grid columns by default; a tile takes one, unwrapped.
                .contains("field=\"status\"\n          labels={ TicketStatusTypeLabels }\n          className=\"sm:col-span-2\"")
                .contains("title={ t('xByY', { x: 'Tickets', y: 'Priority' }) }")
                .contains("title={ t('recentX', { x: 'Tickets' }) }")
                .contains("sortField=\"id\"\n          displayField=\"subject\"\n          limit={ 5 }")
                // No period picker on this dashboard: no state, no params.
                .doesNotContain("useState")
                .doesNotContain("params=");
        assertThat(files.get(FE + "src/shared/ui/widgets.tsx"))
                .contains("export function KpiTile(")
                .contains("export function BreakdownCard(")
                .contains("export function RecentList(");

        // Tabs embed hidden list pages; those pass preset filters into the entity page.
        String queue = files.get(FE + "src/app/screens/QueueScreen.tsx");
        assertThat(queue)
                .contains("import { TicketsOpenScreen } from './TicketsOpenScreen'")
                .contains("{ id: 'tickets-in-progress', label: 'In progress' },")
                .contains("aria-label={ 'Ticket queue' }")
                .contains("{active === 2 && (")
                .contains("<TicketsAllScreen />")
                .doesNotContain("onNavigate")
                .doesNotContain("@shared/i18n");
        assertThat(files.get(FE + "src/app/screens/TicketsOpenScreen.tsx"))
                .isEqualTo("import { TicketPage } from '@pages/ticket'\n"
                        + "import type { FilterValues } from '@shared/ui'\n\n"
                        + "interface Props {\n"
                        + "  /** Filters from the route (#/<page>?<field>=<value>), on top of the page's own preset. */\n"
                        + "  filters?: FilterValues\n"
                        + "}\n\n"
                        + "export function TicketsOpenScreen({ filters }: Props) {\n"
                        + "  // A different filter set in the route is a fresh list, not an edit of the open one.\n"
                        + "  return (\n"
                        + "    <TicketPage\n"
                        + "      key={JSON.stringify(filters ?? {})}\n"
                        + "      initialFilters={ { status: 'OPEN', ...filters } }\n"
                        + "    />\n"
                        + "  )\n"
                        + "}\n");
        assertThat(files.get(FE + "src/app/screens/TicketsAllScreen.tsx"))
                .contains("initialFilters={filters}");
        assertThat(files.get(FE + "src/pages/ticket/ui/TicketPage.tsx"))
                .contains("export function TicketPage({ initialFilters, scope, onOpenRecord }: TicketPageProps = {}) {")
                .contains("useState<FilterValues>(initialFilters ?? {})");
        // An entity without relations takes neither filters nor a scope.
        assertThat(files.get(FE + "src/pages/team/ui/TeamPage.tsx"))
                .contains("export function TeamPage({ onOpenRecord }: TeamPageProps = {}) {")
                .doesNotContain("scope");

        // Master-detail: teams on the left, the selected team's tickets on the right.
        assertThat(files.get(FE + "src/app/screens/TeamsScreen.tsx"))
                .contains("import { useTeam } from '@entities/team'")
                .contains("import { TicketPage } from '@pages/ticket'")
                .contains("export function TeamsScreen() {")
                .contains("useTeam({ page, size: PAGE_SIZE, sort: null, q })")
                .contains("row.name == null || row.name === '' ? '#' + String(row.id) : String(row.name)")
                .contains("scope={ { param: 'teamId', value: selected.id as string | number } }")
                .contains("hint={t('pickXToSeeY', { x: 'Teams', y: 'Tickets' })}")
                .doesNotContain("onNavigate")
                .doesNotContain("ArrowUpRight");

        // Chrome strings the widgets read ship in both tables.
        assertThat(files.get(FE + "src/shared/i18n/strings.ts"))
                .contains("recentX: 'Recent {x}'")
                .contains("viewAll: 'הצג הכל'");
    }

    @Test
    void fullstackEndpoint_withoutPagesKeepsTheClassicShell() throws Exception {
        Map<String, Object> body = exampleBody("tickets", "react-tailwind-crud");
        body.remove("pages");
        Map<String, String> files = generate(body);

        assertThat(files.get(FE + "src/app/App.tsx"))
                .contains("import { LayoutDashboard, Menu, Moon, Sun, Table2 } from 'lucide-react'")
                .contains("const go = (id: View) => {")
                .contains("{current?.label ?? t('dashboard')}")
                .doesNotContain("goView")
                .contains("import { DashboardPage } from '@pages/dashboard'")
                .contains("type View = 'dashboard' | 'team' | 'agent' | 'ticket'")
                .contains("useState<View>('dashboard')")
                .doesNotContain("Screen");
        assertThat(files.keySet()).noneMatch(p -> p.contains("/screens/") || p.endsWith("widgets.tsx"));
        assertThat(files.get(FE + "src/pages/ticket/ui/TicketPage.tsx"))
                .contains("export function TicketPage() {")
                .contains("useState<FilterValues>({})")
                .contains("q: debouncedSearch, filters })")
                .contains("<FilterBar filters={filterDescriptors} values={filters} onChange={setFilters} />")
                .contains("onView={setDetailRow}")
                .doesNotContain("scope")
                .doesNotContain("openRow");
    }

    @Test
    void fullstackEndpoint_menoraSetSkinsTabsPagesAndBorrowsTheRest() throws Exception {
        Map<String, String> tickets = generate(exampleBody("tickets", "react-menora-digital-crud"));
        assertThat(tickets.get(FE + "src/app/screens/QueueScreen.tsx"))
                .contains("import { Tabs } from '@shared/ui/menora'")
                .contains("{ id: 'tickets-open', label: 'Open', panelId: 'tickets-open-panel' },")
                .contains("<Tabs items={TABS} activeIndex={active} onChange={setActive} ariaLabel={ 'Ticket queue' } bare />");
        // Grouped nav: a group is a caret item opening a DropdownMenu of its pages' links.
        assertThat(tickets.get(FE + "src/app/App.tsx"))
                .contains("import { DropdownMenu, NavLinks, ThemeToggle, Footer, useMenoraTheme } from '@shared/ui/menora'")
                .contains("<nav className=\"mn mn-nav\" aria-label={t('main')}>")
                .contains("groups={[{ items: section.items.map(({ id, label }) => ({ label, href: `#/${id}` })) }]}")
                .contains("<NavLinks ariaLabel={section.label || t('main')} items={linksOf(section.items)} stacked />")
                .doesNotContain("const navItems");

        Map<String, String> files = generate(exampleBody("orders", "react-menora-digital-crud"));
        assertThat(files.get(FE + "src/app/App.tsx"))
                .contains("import { OrderScreen } from '@app/screens/OrderScreen'")
                .contains("{ id: 'desk', label: 'Sales desk' },")
                .contains("const go = (id: View, arg?: string, query: Record<string, string> = {}) => {")
                .contains("{view === 'order' && route.arg && <OrderScreen key={route.arg} recordId={route.arg} onNavigate={goView} />}")
                .contains("{current?.label ?? RECORD_TITLES[view] ?? t('dashboard')}")
                .contains("items.map(({ id, label }) => ({ label, href: `#/${id}`, current: view === id, onClick: () => go(id) }))")
                .doesNotContain("DashboardPage");
        assertThat(files.get(FE + "src/app/screens/DeskScreen.tsx"))
                .contains("<p className=\"mt-1 max-w-2xl text-sm text-muted\">{ 'Orders at a glance: volume, status mix and the latest orders.' }</p>")
                .contains("path=\"/api/orders\"\n          onOpen={() => onNavigate('orders')}")
                .contains("path=\"/api/customers\"\n          onOpen={() => onNavigate('customers')}");
        assertThat(files.get(FE + "src/app/screens/CustomersScreen.tsx")).contains("<OrderPage");
        assertThat(files.get(FE + "src/app/screens/OrderScreen.tsx")).contains("<OrderLinePage");
        // The Menora entity page takes the same page-mode props.
        assertThat(files.get(FE + "src/pages/order/ui/OrderPage.tsx"))
                .contains("scope?: { param: string; value: string | number }")
                .contains("onView={openRow}");
        assertThat(files.get(FE + "src/shared/ui/widgets.tsx")).contains("export function KpiTile(");
    }

    @Test
    void fullstackEndpoint_rendersMasterDetailAndRecordPages() throws Exception {
        Map<String, String> files = generate(exampleBody("orders", "react-tailwind-crud"));

        // Shell: the record page is routable (with the row's id) but stays out of the nav.
        String app = files.get(FE + "src/app/App.tsx");
        assertThat(app)
                .contains("import { OrderScreen } from '@app/screens/OrderScreen'")
                .contains("import { LayoutDashboard, ListChecks, Menu, Moon, Package, ShoppingCart, Sun, Users } from 'lucide-react'")
                .contains("{ id: 'customers', label: 'Customers', icon: Users },")
                .contains("const RECORD_TITLES: Partial<Record<View, string>> = {\n  'order': 'Order',\n}")
                .contains("const go = (id: View, arg?: string, query: Record<string, string> = {}) => {\n"
                        + "    navigate({ view: id, arg, query })\n")
                .contains("const goView = (v: string, arg?: string, query?: Record<string, string>) => go(v as View, arg, query)")
                .contains("{view === 'orders' && <OrdersScreen filters={route.query} onNavigate={goView} />}")
                .contains("{view === 'order' && route.arg && <OrderScreen key={route.arg} recordId={route.arg} onNavigate={goView} />}")
                .contains("{current?.label ?? RECORD_TITLES[view] ?? t('dashboard')}")
                .doesNotContain("{ id: 'order',");
        assertThat(files.get(FE + "src/app/route.ts"))
                .contains("export type View = 'desk' | 'orders' | 'customers' | 'order-lines' | 'products' | 'order'")
                .contains("const RECORD_VIEWS: readonly View[] = ['order']");

        // Rows of an entity with a record page open it; its dashboard recents link there too.
        assertThat(files.get(FE + "src/app/screens/OrdersScreen.tsx"))
                .contains("onNavigate: (view: string, arg?: string, query?: Record<string, string>) => void")
                .contains("export function OrdersScreen({ filters, onNavigate }: Props) {")
                .contains("      initialFilters={filters}\n      onOpenRecord={r => onNavigate('order', String(r.id))}\n");
        assertThat(files.get(FE + "src/app/screens/ProductsScreen.tsx"))
                .contains("export function ProductsScreen({ filters }: Props) {")
                .doesNotContain("onNavigate");
        assertThat(files.get(FE + "src/app/screens/DeskScreen.tsx"))
                .contains("limit={ 6 }\n          className=\"sm:col-span-2\"\n          onOpenRow={r => onNavigate('order', String(r['id']))}");
        assertThat(files.get(FE + "src/shared/ui/widgets.tsx"))
                .contains("onOpenRow?: (row: Record<string, unknown>) => void");

        // Master-detail: customers, and the selected customer's orders (which open their record page).
        assertThat(files.get(FE + "src/app/screens/CustomersScreen.tsx"))
                .contains("import { useEffect, useState } from 'react'")
                .contains("export function CustomersScreen({ onNavigate }: Props) {")
                .contains("scope={ { param: 'customerId', value: selected.id as string | number } }")
                .contains("onOpenRecord={r => onNavigate('order', String(r.id))}")
                .contains("{ 'Pick a customer to see and add their orders.' }")
                .doesNotContain("ArrowUpRight");

        // Record page: fetched by id, details tab + one tab per related list, back to the list.
        String record = files.get(FE + "src/app/screens/OrderScreen.tsx");
        assertThat(record)
                .contains("import { ArrowLeft } from 'lucide-react'")
                .contains("import type { Order } from '@entities/order'")
                .contains("import { OrderDetail } from '@features/order-form'")
                .contains("import { OrderLinePage } from '@pages/order-line'")
                .contains("export function OrderScreen({ recordId, onNavigate }: Props) {")
                .contains("api.get<Order>('/api/orders/' + encodeURIComponent(recordId))")
                .contains("{ id: 'details', label: t('xDetails', { x: 'Order' }) },")
                .contains("{ id: 'order-line', label: 'OrderLines' },")
                .contains(": record.reference == null || record.reference === '' ? '#' + String(record.id) : String(record.reference)")
                .contains("onClick={() => onNavigate('orders')}")
                .contains("{active === 1 && (")
                .contains("scope={ { param: 'orderId', value: record.id as string | number } }");

        // The child entity page in page mode: pinned relation filter, pre-filled on New.
        String orderLines = files.get(FE + "src/pages/order-line/ui/OrderLinePage.tsx");
        assertThat(orderLines)
                .contains("interface OrderLinePageProps {")
                .contains("scope?: { param: string; value: string | number }")
                .contains("const openRow = onOpenRecord ?? setDetailRow")
                .contains("const scopedFilters = scope ? { ...filters, [scope.param]: String(scope.value) } : filters")
                .contains("q: debouncedSearch, filters: scopedFilters })")
                .contains("<FilterBar filters={visibleFilters} values={filters} onChange={setFilters} />")
                .contains("if (scope) record[scope.param] = scope.value")
                .contains("setEditing(newRecord())")
                .contains("onView={openRow}");
        assertThat(files.get(FE + "src/shared/i18n/strings.ts"))
                .contains("pickXToSeeY: 'Pick one of the {x} to see its {y}.'")
                .contains("back: 'חזרה'");
    }

    @Test
    void fullstackEndpoint_recordPageWithoutRelatedListsOrHome() throws Exception {
        Map<String, Object> body = exampleBody("tickets", "react-tailwind-crud");
        pages(body).add(new LinkedHashMap<>(Map.of("id", "agent", "type", "record", "entity", "Agent", "childTabs", List.of())));
        pages(body).removeIf(p -> "agents".equals(p.get("id")));
        Map<String, String> files = generate(body);

        String record = files.get(FE + "src/app/screens/AgentScreen.tsx");
        assertThat(record)
                .contains("export function AgentScreen({ recordId }: Props) {")
                .contains("<AgentDetail value={record} />")
                .doesNotContain("TABS")
                .doesNotContain("onNavigate")
                .doesNotContain("lucide-react");
        assertThat(files.get(FE + "src/app/App.tsx"))
                .contains("{view === 'agent' && route.arg && <AgentScreen key={route.arg} recordId={route.arg} />}");
        // A record page needs an id: without one the route falls back to the start page.
        assertThat(files.get(FE + "src/app/route.ts"))
                .contains("const RECORD_VIEWS: readonly View[] = ['agent']")
                .contains("if (!view || (RECORD_VIEWS.includes(view) && !arg)) return { view: 'overview', query: {} }");
    }

    @Test
    void fullstackEndpoint_masterDetailPicksTheNamedRelation() throws Exception {
        Map<String, Object> body = withTicketReporter(exampleBody("tickets", "react-tailwind-crud"));
        pages(body).add(new LinkedHashMap<>(Map.of("id", "by-reporter", "type", "master-detail",
                "parent", "agent", "child", "ticket", "via", "Reporter")));
        Map<String, String> files = generate(body);

        assertThat(files.get(FE + "src/app/screens/ByReporterScreen.tsx"))
                .contains("scope={ { param: 'reporterId', value: selected.id as string | number } }")
                .contains("{ 'Agents' }");
    }

    @Test
    void fullstackEndpoint_escapesUserTextInPageLabels() throws Exception {
        Map<String, Object> body = exampleBody("tickets", "react-tailwind-crud");
        List<Map<String, Object>> pages = pages(body);
        pages.get(0).put("title", "Agent's \"desk\"\nnow");
        pages.get(5).put("group", "People's");
        Map<String, String> files = generate(body);

        assertThat(files.get(FE + "src/app/App.tsx"))
                .contains("{ id: 'overview', label: 'Agent\\'s \"desk\"\\nnow', icon: LayoutDashboard },")
                .contains("label: 'People\\'s',");
    }

    @Test
    void fullstackEndpoint_rendersReportPageAndAggregateWidgets() throws Exception {
        Map<String, Object> body = exampleBody("reporting", "react-tailwind-crud");
        // The example ships settings.scaffold = [csvExport]; exampleBody carries entities and
        // pages only, so the opt is set here for the report's Export button.
        body.put("opts", Map.of("scaffold", List.of("csvExport")));
        Map<String, String> files = generate(body);

        // The report screen: a filter bar, the bar chart of the rollup, and the totals table.
        String report = files.get(FE + "src/app/screens/RevenueScreen.tsx");
        assertThat(report)
                .contains("const PATH = '/api/sales'")
                .contains("const ROLLUP = 'groupBy=region&agg=sum&field=amount'")
                .contains("import { BarRows } from '@shared/ui/widgets'")
                .contains("import { formatStat, statLabel, statsQuery, useStats } from '@shared/ui/stats'")
                .contains("import { SaleRegionTypeLabels } from '@entities/sale'")
                .contains("const filterDescriptors: FilterDescriptor[] = [")
                .contains("<FilterBar filters={filterDescriptors} values={filters} onChange={setFilters} />")
                .contains("<BarRows data={rows} />")
                .contains("{t('total')}")
                .contains("{ t('aggSum', { x: 'Amount' }) }")
                .doesNotContain("<LineChart");

        // csvExport is on for this example, so the report offers the same filters as a download.
        assertThat(report)
                .contains("import { Download } from 'lucide-react'")
                .contains("api.download(`${PATH}/export.csv${search ? `?${search}` : ''}`, 'sales.csv')");

        // The dashboard: a counting tile, reducing tiles, a reducing bar and a trend — all limited
        // to the period picker's window over soldOn; one tile also to a preset region.
        String dashboard = files.get(FE + "src/app/screens/ReportScreen.tsx");
        assertThat(dashboard)
                .contains("import { useState } from 'react'")
                .contains("import { BreakdownCard, KpiTile, PeriodSelect, TrendCard, RecentList, } from '@shared/ui/widgets'")
                .contains("import { rangeParams, statsQuery, type Period } from '@shared/ui/stats'")
                .contains("const [period, setPeriod] = useState<Period>('12m')")
                .contains("<PeriodSelect value={period} onChange={setPeriod} />")
                .contains("title={ 'Sales' }\n          path=\"/api/sales\"\n          params={ rangeParams('soldOn', false, period) }\n")
                .contains("params={ statsQuery('region=NORTH', rangeParams('soldOn', false, period)) }")
                // span 4 for the trend, and the recent list ordered by date with the key kept apart.
                .contains("className=\"sm:col-span-2 lg:col-span-4\"")
                .contains("sortField=\"soldOn\"\n          keyField=\"id\"\n          displayField=\"reference\"")
                .contains("agg=\"sum\"")
                .contains("agg=\"avg\"")
                .contains("field=\"amount\"")
                .contains("<TrendCard")
                .contains("on=\"soldOn\"")
                .contains("bucket=\"month\"")
                .contains("valueField=\"amount\"");

        // The shared widgets ship for a report even with no dashboard, and no longer sample rows.
        String widgets = files.get(FE + "src/shared/ui/widgets.tsx");
        assertThat(widgets)
                .contains("export function PeriodSelect(")
                .contains("api.get<{ totalElements: number }>(`${path}?${statsQuery('size=1', params)}`)")
                .contains("export function LineChart(")
                .contains("export function TrendCard(")
                .doesNotContain("BREAKDOWN_SAMPLE");

        // A report is an ordinary nav page, with its own icon.
        assertThat(files.get(FE + "src/app/App.tsx"))
                .contains("BarChart3")
                .contains("{ id: 'revenue', label: 'Revenue analysis', icon: BarChart3 },");
    }

    @Test
    void fullstackEndpoint_reportOverTimeDrawsALineAndCountsRows() throws Exception {
        Map<String, Object> body = exampleBody("reporting", "react-tailwind-crud");
        List<Map<String, Object>> pages = pages(body);
        // Same page, grouped over the date column and counting rather than reducing.
        pages.get(2).put("chart", Map.of("groupBy", "soldOn", "bucket", "month"));
        Map<String, String> files = generate(body);

        assertThat(files.get(FE + "src/app/screens/RevenueScreen.tsx"))
                .contains("const ROLLUP = 'groupBy=soldOn&bucket=month'")
                .contains("import { LineChart } from '@shared/ui/widgets'")
                // Counting over a date: no enum labels, so statLabel is not imported either.
                .contains("import { formatStat, statsQuery, useStats } from '@shared/ui/stats'")
                .contains("<LineChart data={rows} />")
                // Counting rows, so the value column is headed "Rows" and no labels are imported.
                .contains("{ t('rows') }")
                .doesNotContain("@entities/sale")
                .doesNotContain("<BarRows");
    }

    @Test
    void fullstackEndpoint_shipsWidgetsForAReportWithoutADashboard() throws Exception {
        Map<String, Object> body = exampleBody("reporting", "react-tailwind-crud");
        List<Map<String, Object>> pages = pages(body);
        // Drop the dashboard: widgets.tsx is gated on hasWidgets, not hasDashboardPages.
        pages.remove(0);
        Map<String, String> files = generate(body);

        assertThat(files).containsKey(FE + "src/shared/ui/widgets.tsx");
        assertThat(files).containsKey(FE + "src/shared/ui/stats.ts");
        assertThat(files).containsKey(FE + "src/app/screens/RevenueScreen.tsx");
        assertThat(files.keySet()).noneMatch(k -> k.endsWith("ReportScreen.tsx"));
    }

    @Test
    void fullstackEndpoint_rejectsInvalidPages() {
        assertRejected(p -> p.get(0).put("type", "wizard"), "type 'wizard' is not supported yet");
        assertRejected(p -> p.get(0).put("type", "gallery"), "unknown type 'gallery'");
        assertRejected(p -> p.get(0).put("id", "Overview"), "Page id 'Overview' must be lower-case");
        assertRejected(p -> p.get(5).put("id", "overview"), "Duplicate page id 'overview'");
        assertRejected(p -> p.get(5).put("entity", "Customer"), "unknown entity 'Customer'");
        assertRejected(p -> p.get(0).put("entity", "Ticket"), "(dashboard) does not take 'entity'");
        assertRejected(p -> p.get(0).put("widgets", List.of()), "needs at least one widget");
        assertRejected(p -> p.get(0).put("widgets", List.of(Map.of("kind", "bar", "entity", "Ticket", "groupBy", "subject"))),
                "groupBy 'subject' must be a non-key enum or boolean field");
        assertRejected(p -> p.get(0).put("widgets", List.of(Map.of("kind", "bar", "entity", "Team"))),
                "Team has no enum or boolean field to group by");
        assertRejected(p -> p.get(0).put("widgets", List.of(Map.of("kind", "kpi", "entity", "Ticket", "agg", "sum"))),
                "agg 'sum' needs a numeric 'field' of Ticket to reduce");
        assertRejected(p -> p.get(0).put("widgets", List.of(Map.of("kind", "kpi", "entity", "Ticket",
                        "agg", "count", "field", "subject"))),
                "agg 'count' counts records, so it takes no 'field'");
        assertRejected(p -> p.get(0).put("widgets", List.of(Map.of("kind", "kpi", "entity", "Ticket",
                        "agg", "sum", "field", "subject"))),
                "field 'subject' must be a non-key numeric field to be aggregated");
        assertRejected(p -> p.get(0).put("widgets", List.of(Map.of("kind", "kpi", "entity", "Ticket", "agg", "median"))),
                "unknown agg 'median' (expected count, sum, avg, min or max)");
        assertRejected(p -> p.get(0).put("widgets", List.of(Map.of("kind", "pie", "entity", "Ticket"))),
                "unknown widget kind 'pie' (expected kpi, bar, line or recent)");
        // line widgets plot a temporal field, bucketed
        assertRejected(p -> p.get(0).put("widgets", List.of(Map.of("kind", "line", "entity", "Team"))),
                "Team has no date field to plot over time");
        assertRejected(p -> p.get(0).put("widgets", List.of(Map.of("kind", "line", "entity", "Ticket",
                        "groupBy", "status"))),
                "groupBy 'status' must be a non-key date field to plot over time");
        assertRejected(p -> p.get(0).put("widgets", List.of(Map.of("kind", "line", "entity", "Ticket",
                        "bucket", "fortnight"))),
                "unknown bucket 'fortnight' (expected day, month or year)");
        assertRejected(p -> p.get(0).put("widgets", List.of(Map.of("kind", "bar", "entity", "Ticket",
                        "groupBy", "status", "bucket", "month"))),
                "only a line widget takes 'bucket'");
        assertRejected(p -> p.get(0).put("widgets", List.of(Map.of("kind", "recent", "entity", "Ticket",
                        "agg", "sum", "field", "id"))),
                "a recent widget lists rows, so it takes no 'agg'");
        assertRejected(p -> p.get(0).put("widgets", List.of(Map.of("kind", "recent", "entity", "Ticket", "limit", 99))),
                "limit must be between 1 and 20");
        assertRejected(p -> p.get(1).put("tabs", List.of(Map.of("page", "tickets-open"))), "needs between 2 and 6 tabs");
        assertRejected(p -> p.get(1).put("tabs", List.of(Map.of("page", "tickets-open"), Map.of("page", "queue"))),
                "a tab cannot embed another tabs page ('queue')");
        assertRejected(p -> p.get(1).put("tabs", List.of(Map.of("page", "tickets-open"), Map.of("page", "nope"))),
                "no page with id 'nope'");
        assertRejected(p -> p.get(1).remove("title"), "Page 'queue' (tabs) needs a title");
        assertRejected(p -> p.get(2).put("presetFilter", Map.of("status", "LOST")), "'LOST' is not one of");
        assertRejected(p -> p.get(2).put("presetFilter", Map.of("subject", "x")),
                "only filterable enum or boolean fields can be preset");
        assertRejected(p -> p.forEach(page -> {
            page.put("hidden", true);
            page.remove("group");
            page.remove("icon");
        }), "At least one page must be visible");
        // Master-detail
        assertRejected(p -> p.get(6).put("parent", "Ticket"), "Page 'teams' (master-detail): Ticket has no relation to Ticket");
        assertRejected(p -> p.get(6).put("via", "assignee"), "via 'assignee' is not a relation of Ticket to Team");
        assertRejected(p -> p.get(6).remove("child"), "Page 'teams' (master-detail) child: entity is required");
        assertRejected(p -> p.get(6).put("entity", "Team"), "(master-detail) does not take 'entity'");
        assertRejected(p -> p.get(5).put("parent", "Team"), "(entity-list) does not take 'parent'");
        // Record
        assertRejected(p -> p.add(recordPage("ticket", "Ticket", false)), "cannot be in the navigation");
        assertRejected(p -> {
            p.add(recordPage("ticket", "Ticket", null));
            p.add(recordPage("ticket-again", "Ticket", null));
        }, "Ticket already has a record page ('ticket')");
        assertRejected(p -> {
            p.add(recordPage("ticket", "Ticket", null));
            p.get(1).put("tabs", List.of(Map.of("page", "tickets-open"), Map.of("page", "ticket")));
        }, "a tab cannot embed a record page ('ticket')");
        assertRejected(p -> {
            Map<String, Object> page = recordPage("team", "Team", null);
            page.put("childTabs", List.of("Ticket", "Ticket"));
            p.add(page);
        }, "Ticket is already a tab");
        assertRejected(p -> {
            Map<String, Object> page = recordPage("ticket", "Ticket", null);
            page.put("childTabs", List.of("Team"));
            p.add(page);
        }, "Team has no relation to Ticket");
        assertRejected(p -> p.get(0).put("childTabs", List.of("Team")), "(dashboard) does not take 'childTabs'");
        // Report
        assertRejected(p -> p.add(reportPage("by-status", "Ticket", null)), "a report needs a 'chart'");
        assertRejected(p -> p.add(reportPage("by-status", "Ticket", Map.of("groupBy", "subject"))),
                "groupBy 'subject' must be a non-key enum, boolean or date field");
        assertRejected(p -> p.add(reportPage("by-status", "Team", Map.of())),
                "Team has no enum, boolean or date field to group by");
        assertRejected(p -> p.add(reportPage("by-status", "Ticket", Map.of("groupBy", "status", "bucket", "month"))),
                "'bucket' applies to a date groupBy, and 'status' is not one");
        assertRejected(p -> p.get(0).put("chart", Map.of("groupBy", "status")),
                "(dashboard) does not take 'chart'");
        // Nav sections and icons
        assertRejected(p -> p.get(0).put("icon", "Rocket"), "Page 'overview': unknown icon 'Rocket' (expected one of BarChart3,");
        assertRejected(p -> p.get(2).put("icon", "Inbox"), "Page 'tickets-open' is hidden, so it takes no nav 'icon'");
        assertRejected(p -> p.get(2).put("group", "Work"), "Page 'tickets-open' is hidden, so it takes no nav 'group'");
        assertRejected(p -> p.get(0).put("group", "x".repeat(41)), "Page 'overview' group must be at most 40 characters");
        // Dashboard layout and filters
        assertRejected(p -> p.get(0).put("widgets", List.of(Map.of("kind", "kpi", "entity", "Ticket", "span", 5))),
                "Page 'overview' widgets[0]: span must be between 1 and 4");
        assertRejected(p -> p.get(0).put("widgets", List.of(Map.of("kind", "kpi", "entity", "Ticket", "sortBy", "id"))),
                "only a recent widget takes 'sortBy'");
        assertRejected(p -> p.get(0).put("widgets", List.of(Map.of("kind", "recent", "entity", "Ticket", "sortBy", "nope"))),
                "sortBy 'nope' is not a field of Ticket");
        assertRejected(p -> p.get(0).put("widgets", List.of(Map.of("kind", "kpi", "entity", "Ticket",
                        "presetFilter", Map.of("status", "LOST")))),
                "Page 'overview' widgets[0] presetFilter 'status': 'LOST' is not one of");
        assertRejected(p -> p.get(0).put("dateRange", "decade"),
                "unknown dateRange 'decade' (expected all, 7d, 30d, 90d, ytd or 12m)");
        assertRejected(p -> p.get(0).put("widgets", List.of(Map.of("kind", "kpi", "entity", "Ticket", "dateField", "openedOn"))),
                "'dateField' applies to the dashboard's dateRange, which is not set");
        assertRejected(p -> {
            p.get(0).put("dateRange", "30d");
            p.get(0).put("widgets", List.of(Map.of("kind", "kpi", "entity", "Team")));
        }, "has a dateRange, but none of its widgets counts an entity with a filterable date field");
        assertRejected(p -> p.get(5).put("dateRange", "30d"), "(entity-list) does not take 'dateRange'");
    }

    @Test
    void fullstackEndpoint_rejectsAmbiguousOrCompositeKeyLayouts() {
        Map<String, Object> ambiguous = withTicketReporter(exampleBody("tickets", "react-tailwind-crud"));
        pages(ambiguous).add(new LinkedHashMap<>(Map.of("id", "by-agent", "type", "master-detail",
                "parent", "Agent", "child", "Ticket")));
        assertBadRequest(ambiguous, "Ticket has several relations to Agent [assignee, reporter]; set 'via' to pick one");

        Map<String, Object> composite = exampleBody("tickets", "react-tailwind-crud");
        entities(composite).add(new LinkedHashMap<>(Map.of("name", "Shift", "fields", List.of(
                Map.of("name", "agentCode", "type", "STRING", "primaryKey", true),
                Map.of("name", "day", "type", "LOCAL_DATE", "primaryKey", true)))));
        pages(composite).add(recordPage("shift", "Shift", null));
        assertBadRequest(composite, "Shift has a composite key; only single-key entities can be opened as one record");
    }

    @Test
    void fullstackEndpoint_canonicalizesPresetFilterAndEntityNames() throws Exception {
        Map<String, Object> body = exampleBody("tickets", "react-tailwind-crud");
        List<Map<String, Object>> pages = pages(body);
        pages.get(2).put("entity", "ticket");
        pages.get(2).put("presetFilter", Map.of("status", "open"));
        Map<String, String> files = generate(body);

        assertThat(files.get(FE + "src/app/screens/TicketsOpenScreen.tsx"))
                .contains("initialFilters={ { status: 'OPEN', ...filters } }");
    }

    @Test
    void fullstackEndpoint_dashboardPeriodLimitsOnlyWidgetsWithADate() throws Exception {
        Map<String, Object> body = exampleBody("tickets", "react-tailwind-crud");
        pages(body).get(0).put("dateRange", "ytd");
        Map<String, String> files = generate(body);

        // Ticket's date is a date-time, so the period covers whole days; Agent and Team have no
        // date, so their tiles stay unlimited.
        assertThat(files.get(FE + "src/app/screens/OverviewScreen.tsx"))
                .contains("const [period, setPeriod] = useState<Period>('ytd')")
                .contains("import { rangeParams, type Period } from '@shared/ui/stats'")
                .contains("title={ 'Tickets' }\n          path=\"/api/tickets\"\n          params={ rangeParams('dueAt', true, period) }")
                .contains("title={ 'Agents' }\n          path=\"/api/agents\"\n          onOpen=")
                .doesNotContain("statsQuery");
        assertThat(files.get(FE + "src/shared/ui/stats.ts"))
                .contains("export function rangeParams(field: string, dateTime: boolean, period: Period, previous = false): string {")
                .contains("const to = isoDay(range.to) + (dateTime ? 'T23:59:59' : '')");
        assertThat(files.get(FE + "src/shared/i18n/strings.ts"))
                .contains("periodYtd: 'This year',")
                .contains("periodYtd: 'מתחילת השנה',");
    }

    // ── Helpers ─────────────────────────────────────────────────────────────

    private void assertRejected(Consumer<List<Map<String, Object>>> mutator, String expectedMessage) {
        Map<String, Object> body = exampleBody("tickets", "react-tailwind-crud");
        mutator.accept(pages(body));
        assertBadRequest(body, expectedMessage);
    }

    private void assertBadRequest(Map<String, Object> body, String expectedMessage) {
        ResponseEntity<String> response = restTemplate.exchange("/starter-fullstack.zip", HttpMethod.POST,
                new HttpEntity<>(body, jsonHeaders()), String.class);
        assertThat(response.getStatusCode()).as(expectedMessage).isEqualTo(HttpStatus.BAD_REQUEST);
        assertThat(response.getBody()).contains(expectedMessage);
    }

    @SuppressWarnings("unchecked")
    private static List<Map<String, Object>> pages(Map<String, Object> body) {
        return (List<Map<String, Object>>) body.get("pages");
    }

    @SuppressWarnings("unchecked")
    private static List<Map<String, Object>> entities(Map<String, Object> body) {
        return (List<Map<String, Object>>) body.get("entities");
    }

    private static Map<String, Object> recordPage(String id, String entity, Boolean hidden) {
        Map<String, Object> page = new LinkedHashMap<>(Map.of("id", id, "type", "record", "entity", entity));
        if (hidden != null) page.put("hidden", hidden);
        return page;
    }

    /** A report page over {@code entity}; a null {@code chart} leaves the property off entirely. */
    private static Map<String, Object> reportPage(String id, String entity, Map<String, String> chart) {
        Map<String, Object> page = new LinkedHashMap<>(Map.of("id", id, "type", "report", "entity", entity));
        if (chart != null) page.put("chart", chart);
        return page;
    }

    /** Gives Ticket a second relation to Agent, so Agent → Ticket is ambiguous without {@code via}. */
    @SuppressWarnings("unchecked")
    private static Map<String, Object> withTicketReporter(Map<String, Object> body) {
        List<Map<String, Object>> entities = entities(body);
        for (int i = 0; i < entities.size(); i++) {
            if (!"Ticket".equals(entities.get(i).get("name"))) continue;
            Map<String, Object> ticket = new LinkedHashMap<>(entities.get(i));
            List<Object> relations = new ArrayList<>((List<Object>) ticket.get("relations"));
            relations.add(Map.of("type", "MANY_TO_ONE", "fieldName", "reporter", "targetEntity", "Agent"));
            ticket.put("relations", relations);
            entities.set(i, ticket);
        }
        return body;
    }

    /** A fullstack request built from a seeded example's entities + pages (mutable copies). */
    static Map<String, Object> exampleBody(String exampleId, String frontendSet) {
        try (InputStream in = new ClassPathResource("catalog/fullstack-examples.json").getInputStream()) {
            List<Map<String, Object>> examples = new ObjectMapper().readValue(in, new TypeReference<>() {});
            Map<String, Object> example = examples.stream()
                    .filter(e -> exampleId.equals(e.get("exampleId"))).findFirst().orElseThrow();
            Map<String, Object> body = new LinkedHashMap<>();
            body.put("artifactId", "support");
            body.put("packageName", "com.menora.support");
            body.put("bootVersion", "3.2.1");
            body.put("frontendTemplateSet", frontendSet);
            body.put("entities", new ArrayList<>((List<Map<String, Object>>) example.get("entities")));
            body.put("pages", new ArrayList<>(example.get("pages") == null ? List.of()
                    : ((List<Map<String, Object>>) example.get("pages")).stream()
                            .map(p -> (Map<String, Object>) new LinkedHashMap<>(p)).toList()));
            return body;
        } catch (java.io.IOException e) {
            throw new IllegalStateException(e);
        }
    }

    private Map<String, String> generate(Map<String, Object> body) throws Exception {
        ResponseEntity<byte[]> response = restTemplate.exchange("/starter-fullstack.zip", HttpMethod.POST,
                new HttpEntity<>(body, jsonHeaders()), byte[].class);
        assertThat(response.getStatusCode())
                .as(response.getBody() == null ? "" : new String(response.getBody(), StandardCharsets.UTF_8))
                .isEqualTo(HttpStatus.OK);
        Map<String, String> result = new TreeMap<>();
        try (ZipInputStream zin = new ZipInputStream(new ByteArrayInputStream(response.getBody()))) {
            ZipEntry entry;
            while ((entry = zin.getNextEntry()) != null) {
                if (entry.isDirectory()) continue;
                ByteArrayOutputStream out = new ByteArrayOutputStream();
                zin.transferTo(out);
                result.put(entry.getName(), out.toString(StandardCharsets.UTF_8));
            }
        }
        return result;
    }

    private static HttpHeaders jsonHeaders() {
        HttpHeaders headers = new HttpHeaders();
        headers.setContentType(MediaType.APPLICATION_JSON);
        return headers;
    }
}
