-- V4: Fullstack CRUD scaffolding — template sets and per-set template files.
--
-- A "set" is a named bundle of templates (e.g. "spring-jpa-crud", "react-tailwind-crud").
-- A "file" in a set has a Mustache-rendered path and content; perEntity=true means the
-- file is rendered once per user-defined entity (e.g. UserController.java + OrderController.java
-- from a single template row).

CREATE TABLE entity_template_set (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    set_key VARCHAR(80) NOT NULL,
    name VARCHAR(150) NOT NULL,
    description VARCHAR(500),
    kind VARCHAR(20) NOT NULL,
    enabled BOOLEAN NOT NULL,
    sort_order INTEGER NOT NULL,
    CONSTRAINT uk_entity_template_set_key UNIQUE (set_key)
);

CREATE TABLE entity_template_file (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    set_id BIGINT NOT NULL,
    path_template VARCHAR(500) NOT NULL,
    content CLOB,
    substitution_type VARCHAR(20) NOT NULL,
    file_type VARCHAR(20) NOT NULL,
    per_entity BOOLEAN NOT NULL,
    sort_order INTEGER NOT NULL,
    CONSTRAINT fk_entity_template_file_set FOREIGN KEY (set_id) REFERENCES entity_template_set (id)
);

CREATE INDEX ix_entity_template_file_set ON entity_template_file (set_id);
