-- V5: Per-template-set default dependency IDs.
--
-- When the fullstack wizard picks a backend template set, these dep IDs are
-- pre-checked in the UI's Dependencies section. The FullstackStarterController
-- merges them with any explicit request `dependencies` before applying its
-- hard-coded minimum (data-jpa, web, h2).

CREATE TABLE initializer_entity_template_set_default_dep (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    set_id BIGINT NOT NULL,
    dep_id VARCHAR(120) NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT fk_entity_template_set_default_dep_set
        FOREIGN KEY (set_id) REFERENCES initializer_entity_template_set (id),
    CONSTRAINT uk_entity_template_set_default_dep_set_dep
        UNIQUE (set_id, dep_id)
);

CREATE INDEX ix_entity_template_set_default_dep_set
    ON initializer_entity_template_set_default_dep (set_id);
