-- V15: Move Java / Spring Boot / React / Node / package-manager version lists
-- out of application.yml into a single admin-managed table. Each row is one
-- selectable value for one of the five "kinds". npm_semver and types_semver
-- carry the React-major → npm semver mappings previously hardcoded in
-- FrontendMustacheContext (e.g. React 18 → ^18.3.1) so adding a new React
-- release is a pure data change.

CREATE TABLE initializer_version_definition (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind          VARCHAR(32)  NOT NULL,
    version_id    VARCHAR(64)  NOT NULL,
    display_name  VARCHAR(128) NOT NULL,
    is_default    BOOLEAN      NOT NULL DEFAULT FALSE,
    sort_order    INTEGER      NOT NULL DEFAULT 0,
    enabled       BOOLEAN      NOT NULL DEFAULT TRUE,
    npm_semver    VARCHAR(64),
    types_semver  VARCHAR(64),
    CONSTRAINT uk_version_kind_id UNIQUE (kind, version_id)
);
CREATE INDEX ix_version_kind_sort ON initializer_version_definition (kind, sort_order);
