-- V19: Team-shared fullstack entity models (the Fullstack tab's "Team" presets)

CREATE TABLE initializer_fullstack_model (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    description VARCHAR(500),
    snapshot CLOB NOT NULL,
    entity_count INTEGER NOT NULL,
    created_by VARCHAR(255),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_fullstack_model_name UNIQUE (name)
);

CREATE INDEX idx_fullstack_model_updated_at ON initializer_fullstack_model (updated_at);
