-- V1: Baseline schema — all 10 tables matching Hibernate-generated DDL for H2

CREATE TABLE dependency_group (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    sort_order INTEGER NOT NULL
);

CREATE TABLE dependency_entry (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id BIGINT NOT NULL,
    dep_id VARCHAR(50) NOT NULL,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    maven_group_id VARCHAR(200),
    maven_artifact_id VARCHAR(200),
    version VARCHAR(50),
    scope VARCHAR(20),
    repository VARCHAR(50),
    sort_order INTEGER NOT NULL,
    compatibility_range VARCHAR(100),
    is_starter BOOLEAN,
    CONSTRAINT uk_dependency_entry_dep_id UNIQUE (dep_id),
    CONSTRAINT fk_dependency_entry_group FOREIGN KEY (group_id) REFERENCES dependency_group (id)
);

CREATE TABLE file_contribution (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dependency_id VARCHAR(50) NOT NULL,
    file_type VARCHAR(20) NOT NULL,
    content CLOB,
    target_path VARCHAR(500) NOT NULL,
    substitution_type VARCHAR(20),
    java_version VARCHAR(10),
    sub_option_id VARCHAR(50),
    sort_order INTEGER NOT NULL
);

CREATE TABLE build_customization (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dependency_id VARCHAR(50) NOT NULL,
    customization_type VARCHAR(30) NOT NULL,
    maven_group_id VARCHAR(200),
    maven_artifact_id VARCHAR(200),
    version VARCHAR(50),
    exclude_from_group_id VARCHAR(200),
    exclude_from_artifact_id VARCHAR(200),
    repo_id VARCHAR(50),
    repo_name VARCHAR(200),
    repo_url VARCHAR(500),
    snapshots_enabled BOOLEAN,
    sort_order INTEGER NOT NULL
);

CREATE TABLE dependency_sub_option (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dependency_id VARCHAR(50) NOT NULL,
    option_id VARCHAR(50) NOT NULL,
    label VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    sort_order INTEGER NOT NULL
);

CREATE TABLE dependency_compatibility (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_dep_id VARCHAR(50) NOT NULL,
    target_dep_id VARCHAR(50) NOT NULL,
    relation_type VARCHAR(20) NOT NULL,
    description VARCHAR(500),
    sort_order INTEGER NOT NULL
);

CREATE TABLE starter_template (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template_id VARCHAR(50) NOT NULL,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    icon VARCHAR(50),
    color VARCHAR(20),
    boot_version VARCHAR(20),
    java_version VARCHAR(10),
    packaging VARCHAR(10),
    sort_order INTEGER NOT NULL,
    CONSTRAINT uk_starter_template_template_id UNIQUE (template_id)
);

CREATE TABLE starter_template_dep (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template_id BIGINT NOT NULL,
    dep_id VARCHAR(50) NOT NULL,
    sub_options VARCHAR(500),
    CONSTRAINT fk_starter_template_dep_template FOREIGN KEY (template_id) REFERENCES starter_template (id)
);

CREATE TABLE module_template (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    module_id VARCHAR(50) NOT NULL,
    label VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    suffix VARCHAR(50) NOT NULL,
    packaging VARCHAR(20) NOT NULL,
    has_main_class BOOLEAN NOT NULL,
    sort_order INTEGER NOT NULL,
    CONSTRAINT uk_module_template_module_id UNIQUE (module_id)
);

CREATE TABLE module_dependency_mapping (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dependency_id VARCHAR(50) NOT NULL,
    module_id VARCHAR(50) NOT NULL,
    sort_order INTEGER NOT NULL,
    CONSTRAINT uk_module_dep_mapping UNIQUE (dependency_id, module_id)
);
