-- V20: Add department table — admin-managed list of organisational departments
-- (e.g. lts). The selected department is exposed to every Mustache template as
-- {{department}} / {{departmentUpper}} / {{departmentName}} (k8s values, log4j2
-- topic, ldap group prefix). Shared by the backend, frontend and fullstack screens.

CREATE TABLE initializer_department (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_id VARCHAR(50) NOT NULL,
    name VARCHAR(100) NOT NULL,
    sort_order INTEGER NOT NULL,
    is_default BOOLEAN NOT NULL,
    CONSTRAINT uk_department_department_id UNIQUE (department_id)
);
