-- V21: Admin-managed fullstack "Start from → Examples" models (Blog, Orders, …). Before
-- this they were a hardcoded constant in the UI. `entities` is the JSON array of wire
-- entities (the same shape POST /starter-fullstack.zip takes), validated on every admin save.

CREATE TABLE initializer_fullstack_example (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    example_id VARCHAR(50) NOT NULL,
    name VARCHAR(150) NOT NULL,
    description VARCHAR(500),
    icon VARCHAR(60),
    entities CLOB NOT NULL,
    sort_order INTEGER NOT NULL,
    enabled BOOLEAN NOT NULL,
    CONSTRAINT uk_fullstack_example_example_id UNIQUE (example_id)
);
