-- V2: Generation audit table

CREATE TABLE generation_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_timestamp TIMESTAMP NOT NULL,
    endpoint VARCHAR(64) NOT NULL,
    artifact_id VARCHAR(255),
    group_id VARCHAR(255),
    boot_version VARCHAR(32),
    java_version VARCHAR(16),
    packaging VARCHAR(16),
    language VARCHAR(16),
    dependency_ids CLOB,
    duration_ms BIGINT NOT NULL,
    status VARCHAR(16) NOT NULL,
    error_message VARCHAR(1024),
    remote_addr VARCHAR(64)
);

CREATE INDEX idx_generation_event_timestamp ON generation_event (event_timestamp);
CREATE INDEX idx_generation_event_endpoint ON generation_event (endpoint);
