-- V5: Add color_palette table — admin-managed color schemes selectable when
-- generating a frontend project with a themed design system (MUI / Chakra / Mantine).
--
-- Color columns are suffixed _hex to avoid the reserved keyword PRIMARY.

CREATE TABLE color_palette (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    palette_id VARCHAR(50) NOT NULL,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    primary_hex VARCHAR(7) NOT NULL,
    secondary_hex VARCHAR(7) NOT NULL,
    accent_hex VARCHAR(7),
    error_hex VARCHAR(7),
    sort_order INTEGER NOT NULL,
    is_default BOOLEAN NOT NULL,
    CONSTRAINT uk_color_palette_palette_id UNIQUE (palette_id)
);
