-- V7: color palettes table + default-palette pointer on entity_template_set.
--
-- Wires the previously-orphaned /admin/color-palettes UI tab to a real backend table,
-- and lets a FRONTEND_REACT template set declare a default palette to apply when the
-- chosen design system is palette-aware (MUI / Chakra / Mantine). Tailwind / shadcn /
-- none ignore the palette entirely; the field is still settable to support future
-- design systems.

CREATE TABLE color_palette (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    palette_id VARCHAR(80) NOT NULL,
    name VARCHAR(150) NOT NULL,
    description VARCHAR(500),
    primary_color VARCHAR(7) NOT NULL,
    secondary_color VARCHAR(7) NOT NULL,
    accent VARCHAR(7),
    error_color VARCHAR(7),
    is_default BOOLEAN NOT NULL DEFAULT FALSE,
    sort_order INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT uk_color_palette_palette_id UNIQUE (palette_id)
);

ALTER TABLE entity_template_set ADD COLUMN default_palette_id VARCHAR(80);
