spring:
  security:
    oauth2:
      client:
        registration:
          menora-sso:
            client-id: ${OAUTH2_CLIENT_ID}
            client-secret: ${OAUTH2_CLIENT_SECRET}
            scope: openid,profile,email
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          menora-sso:
            issuer-uri: ${OAUTH2_ISSUER_URI:https://sso.menora.co.il/realms/menora}
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH2_ISSUER_URI:https://sso.menora.co.il/realms/menora}
